/* ptcall.c: generated by interface compiler */

#include "sfcall.h"

typedef struct {
  char *s2h_data;
  char *h2s_data;
  void (*fp)();
} ptxinfo_t;

extern int xcpt_xpt_init(void *fp, ptxinfo_t **, char *);
extern int xcpt_xpt_call(ptxinfo_t *);
extern int xcpt_xpt_return(ptxinfo_t *);
extern int xcpt_ipt_init(void *fp, char *, unsigned *);
extern int xcpt_ipt_return(ptxinfo_t *);
extern int xcpt_set_scope(ptxinfo_t *);


