/* sfcall.c: generated by interface compiler */

#include "sfcall.h"

extern unsigned long long displaySimLtime(int tu, int tp);
extern unsigned displaySimStime(int tu, int tp);

extern void xctf_OSF_get_iargs(int chId, int gpid, void* iargs);
extern void xctf_OSF_put_oargs(int chId, int gpid, void* oargs);
extern const char *xctf_strget(int gid);


#ifdef __cplusplus
extern "C" {
#endif

typedef int (*_zyifsyn_tb_task_2_xpt_callback_fp)(int gpid);
int _zyifsyn_tb_task_2_xpt(int *svgpid)
{
  _zyifsyn_tb_task_2_xpt_callback_fp fp;
  int gpid;
  int retval;
  xctf_ISF_port_info((void *) &_zyifsyn_tb_task_2_xpt, (int **) &fp, &gpid);
  *svgpid = gpid;
  retval = fp(gpid);
  return retval;
}

int _zyifsyn_tb_task_2_xpt_0_2_emu(int gpid)
{

  int disabled;

  // iargs = {a, b}
  // call dut task
  xctf_ISF_task_call_begin(gpid, NULL, NULL);

  return 0;
}

int _zyifsyn_tb_task_2_ipt_p2(int gpid) {

  xctf_ISF_task_call_end(gpid, NULL, NULL);

  // {c, d} = oargs
  return 0;
}

extern int _zyifsyn_tb_task_2_xpt_0_2_sim(int gpid);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif

int _zyifsyn_tb_task_2_ipt(int *gpid) {
  return _zyifsyn_tb_task_2_xpt(gpid);

}


#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
