`begin_keywords "1800-2012"
module cr_kme_ckv_pipeline ( kme_slv_rd, cceip_encrypt_in, cceip_encrypt_in_valid, cceip_validate_in, cceip_validate_in_valid, cddip_decrypt_in, cddip_decrypt_in_valid, ckv_rd, ckv_addr, kim_rd, kim_addr, drng_ack, stat_req_with_expired_seed, stat_aux_key_type_0, stat_aux_key_type_1, stat_aux_key_type_2, stat_aux_key_type_3, stat_aux_key_type_4, stat_aux_key_type_5, stat_aux_key_type_6, stat_aux_key_type_7, stat_aux_key_type_8, stat_aux_key_type_9, stat_aux_key_type_10, stat_aux_key_type_11, stat_aux_key_type_12, stat_aux_key_type_13, stat_aux_cmd_with_vf_pf_fail, tlv_parser_idle, tlv_parser_int_tlv_start_pulse, set_tlv_bip2_error_int, clk, rst_n, disable_debug_cmd_q, disable_unencrypted_keys, always_validate_kim_ref, kme_slv_out, kme_slv_aempty, kme_slv_empty, cceip_encrypt_in_stall, cceip_validate_in_stall, cddip_decrypt_in_stall, ckv_dout, ckv_mbe, kim_dout, kim_mbe, drng_seed_expired, drng_health_fail, drng_256_out, drng_valid );
typedef enum reg  [3 : 0] {KME_WORD0=4'b0,KME_DEBUG_KEYHDR=4'b01,KME_IVTWEAK=4'b010,KME_GUID=4'b011,KME_KIM=4'b0100,KME_DEK_CKV0=4'b0101,KME_DEK_CKV1=4'b0110,KME_DAK_CKV=4'b0111,KME_EIV=4'b1000,KME_DEK0=4'b1001,KME_DEK1=4'b1010,KME_ETAG=4'b1011,KME_AIV=4'b1100,KME_DAK=4'b1101,KME_ATAG=4'b1110,KME_ERROR=4'b1111} kme_internal_id ;
typedef struct packed {logic [0 : 0] sot ; logic [0 : 0] eoi ; logic [0 : 0] eot ; kme_internal_id id ; logic [63 : 0] tdata ;} kme_internal_t ;
typedef struct packed {logic tvalid ; logic tlast ; logic [0 : 0] tid ; logic [7 : 0] tstrb ; logic [7 : 0] tuser ; logic [63 : 0] tdata ;} axi4s_dp_bus_t ;
typedef struct packed {logic [0 : 0] valid ; logic [2 : 0] label_index ; logic [1 : 0] ckv_length ; logic [14 : 0] ckv_pointer ; logic [3 : 0] pf_num ; logic [11 : 0] vf_num ; logic [0 : 0] vf_valid ;} kim_entry_t ;
output wire logic kme_slv_rd ;
output kme_internal_t cceip_encrypt_in ;
output wire logic cceip_encrypt_in_valid ;
output kme_internal_t cceip_validate_in ;
output wire logic cceip_validate_in_valid ;
output kme_internal_t cddip_decrypt_in ;
output wire logic cddip_decrypt_in_valid ;
output wire logic ckv_rd ;
output wire logic [14 : 0] ckv_addr ;
output wire logic kim_rd ;
output wire logic [13 : 0] kim_addr ;
output wire logic drng_ack ;
output wire logic stat_req_with_expired_seed ;
output wire logic stat_aux_key_type_0 ;
output wire logic stat_aux_key_type_1 ;
output wire logic stat_aux_key_type_2 ;
output wire logic stat_aux_key_type_3 ;
output wire logic stat_aux_key_type_4 ;
output wire logic stat_aux_key_type_5 ;
output wire logic stat_aux_key_type_6 ;
output wire logic stat_aux_key_type_7 ;
output wire logic stat_aux_key_type_8 ;
output wire logic stat_aux_key_type_9 ;
output wire logic stat_aux_key_type_10 ;
output wire logic stat_aux_key_type_11 ;
output wire logic stat_aux_key_type_12 ;
output wire logic stat_aux_key_type_13 ;
output wire logic stat_aux_cmd_with_vf_pf_fail ;
output wire logic tlv_parser_idle ;
output wire logic tlv_parser_int_tlv_start_pulse ;
output wire logic set_tlv_bip2_error_int ;
input wire logic clk ;
input wire logic rst_n ;
input wire logic disable_debug_cmd_q ;
input wire logic disable_unencrypted_keys ;
input wire logic always_validate_kim_ref ;
input axi4s_dp_bus_t kme_slv_out ;
input wire logic kme_slv_aempty ;
input wire logic kme_slv_empty ;
input wire logic cceip_encrypt_in_stall ;
input wire logic cceip_validate_in_stall ;
input wire logic cddip_decrypt_in_stall ;
input wire logic [63 : 0] ckv_dout ;
input wire logic ckv_mbe ;
input kim_entry_t kim_dout ;
input wire logic kim_mbe ;
input wire logic drng_seed_expired ;
input wire logic drng_health_fail ;
input wire logic [127 : 0] drng_256_out ;
input wire logic drng_valid ;
endmodule
`end_keywords
/**portGenericDumpBegin kme_internal_id KME_WORD0 KME_DEBUG_KEYHDR KME_IVTWEAK KME_GUID KME_KIM KME_DEK_CKV0 KME_DEK_CKV1 KME_DAK_CKV KME_EIV KME_DEK0 KME_DEK1 KME_ETAG KME_AIV KME_DAK KME_ATAG KME_ERROR kme_internal_t sot eoi eot id tdata axi4s_dp_bus_t tvalid tlast tid tstrb tuser tdata kim_entry_t valid label_index ckv_length ckv_pointer pf_num vf_num vf_valid kme_slv_rd cceip_encrypt_in cceip_encrypt_in_valid cceip_validate_in cceip_validate_in_valid cddip_decrypt_in cddip_decrypt_in_valid ckv_rd ckv_addr kim_rd kim_addr drng_ack stat_req_with_expired_seed stat_aux_key_type_0 stat_aux_key_type_1 stat_aux_key_type_2 stat_aux_key_type_3 stat_aux_key_type_4 stat_aux_key_type_5 stat_aux_key_type_6 stat_aux_key_type_7 stat_aux_key_type_8 stat_aux_key_type_9 stat_aux_key_type_10 stat_aux_key_type_11 stat_aux_key_type_12 stat_aux_key_type_13 stat_aux_cmd_with_vf_pf_fail tlv_parser_idle tlv_parser_int_tlv_start_pulse set_tlv_bip2_error_int clk rst_n disable_debug_cmd_q disable_unencrypted_keys always_validate_kim_ref kme_slv_out kme_slv_aempty kme_slv_empty cceip_encrypt_in_stall cceip_validate_in_stall cddip_decrypt_in_stall ckv_dout ckv_mbe kim_dout kim_mbe drng_seed_expired drng_health_fail drng_256_out drng_valid portGenericDumpEnd**/
/**ParamPreferVectorBegin ParamPreferVectorEnd**/
