`begin_keywords "1800-2012"
module cr_kme_core ( kme_ib_out, kme_cceip0_ob_out, kme_cceip1_ob_out, kme_cceip2_ob_out, kme_cceip3_ob_out, kme_cddip0_ob_out, kme_cddip1_ob_out, kme_cddip2_ob_out, kme_cddip3_ob_out, ckv_rd, ckv_addr, kim_rd, kim_addr, cceip_encrypt_bimc_osync, cceip_encrypt_bimc_odat, cceip_encrypt_mbe, cceip_validate_bimc_osync, cceip_validate_bimc_odat, cceip_validate_mbe, cddip_decrypt_bimc_osync, cddip_decrypt_bimc_odat, cddip_decrypt_mbe, axi_bimc_osync, axi_bimc_odat, axi_mbe, seed0_invalidate, seed1_invalidate, set_txc_bp_int, set_gcm_tag_fail_int, set_key_tlv_miscmp_int, set_tlv_bip2_error_int, set_rsm_is_backpressuring, idle_components, sa_snapshot, sa_count, kme_idle, clk, rst_n, scan_en, scan_mode, scan_rst_n, disable_debug_cmd, disable_unencrypted_keys, suppress_key_tlvs, always_validate_kim_ref, kme_ib_in, kme_cceip0_ob_in, kme_cceip1_ob_in, kme_cceip2_ob_in, kme_cceip3_ob_in, kme_cddip0_ob_in, kme_cddip1_ob_in, kme_cddip2_ob_in, kme_cddip3_ob_in, ckv_dout, ckv_mbe, kim_dout, kim_mbe, bimc_rst_n, cceip_encrypt_bimc_isync, cceip_encrypt_bimc_idat, cceip_validate_bimc_isync, cceip_validate_bimc_idat, cddip_decrypt_bimc_isync, cddip_decrypt_bimc_idat, axi_bimc_isync, axi_bimc_idat, labels, seed0_valid, seed0_internal_state_key, seed0_internal_state_value, seed0_reseed_interval, seed1_valid, seed1_internal_state_key, seed1_internal_state_value, seed1_reseed_interval, tready_override, cceip_encrypt_kop_fifo_override, cceip_validate_kop_fifo_override, cddip_decrypt_kop_fifo_override, kdf_test_key_size, kdf_test_mode_en, sa_global_ctrl, sa_ctrl );
parameter KME_STUB = 0 ;
typedef struct packed {logic tready ;} axi4s_dp_rdy_t ;
typedef struct packed {logic tvalid ; logic tlast ; logic [0 : 0] tid ; logic [7 : 0] tstrb ; logic [7 : 0] tuser ; logic [63 : 0] tdata ;} axi4s_dp_bus_t ;
typedef struct packed {logic [0 : 0] valid ; logic [2 : 0] label_index ; logic [1 : 0] ckv_length ; logic [14 : 0] ckv_pointer ; logic [3 : 0] pf_num ; logic [11 : 0] vf_num ; logic [0 : 0] vf_valid ;} kim_entry_t ;
typedef struct packed {logic [0 : 0] guid_size ; logic [5 : 0] label_size ; logic [255 : 0] label ; logic [0 : 0] delimiter_valid ; logic [7 : 0] delimiter ;} label_t ;
output axi4s_dp_rdy_t kme_ib_out ;
output axi4s_dp_bus_t kme_cceip0_ob_out ;
output axi4s_dp_bus_t kme_cceip1_ob_out ;
output axi4s_dp_bus_t kme_cceip2_ob_out ;
output axi4s_dp_bus_t kme_cceip3_ob_out ;
output axi4s_dp_bus_t kme_cddip0_ob_out ;
output axi4s_dp_bus_t kme_cddip1_ob_out ;
output axi4s_dp_bus_t kme_cddip2_ob_out ;
output axi4s_dp_bus_t kme_cddip3_ob_out ;
output wire logic ckv_rd ;
output wire logic [14 : 0] ckv_addr ;
output wire logic kim_rd ;
output wire logic [13 : 0] kim_addr ;
output wire logic cceip_encrypt_bimc_osync ;
output wire logic cceip_encrypt_bimc_odat ;
output wire logic cceip_encrypt_mbe ;
output wire logic cceip_validate_bimc_osync ;
output wire logic cceip_validate_bimc_odat ;
output wire logic cceip_validate_mbe ;
output wire logic cddip_decrypt_bimc_osync ;
output wire logic cddip_decrypt_bimc_odat ;
output wire logic cddip_decrypt_mbe ;
output wire logic axi_bimc_osync ;
output wire logic axi_bimc_odat ;
output wire logic axi_mbe ;
output wire logic seed0_invalidate ;
output wire logic seed1_invalidate ;
output wire logic set_txc_bp_int ;
output wire logic set_gcm_tag_fail_int ;
output wire logic set_key_tlv_miscmp_int ;
output wire logic set_tlv_bip2_error_int ;
output wire logic [7 : 0] set_rsm_is_backpressuring ;
output cr_kme_regfilePKG::idle_t idle_components ;
output cr_kme_regfilePKG::sa_snapshot_t sa_snapshot[31 : 0] ;
output cr_kme_regfilePKG::sa_count_t sa_count[31 : 0] ;
output wire logic kme_idle ;
input wire logic clk ;
input wire logic rst_n ;
input wire logic scan_en ;
input wire logic scan_mode ;
input wire logic scan_rst_n ;
input wire logic disable_debug_cmd ;
input wire logic disable_unencrypted_keys ;
input wire logic suppress_key_tlvs ;
input wire logic always_validate_kim_ref ;
input axi4s_dp_bus_t kme_ib_in ;
input axi4s_dp_rdy_t kme_cceip0_ob_in ;
input axi4s_dp_rdy_t kme_cceip1_ob_in ;
input axi4s_dp_rdy_t kme_cceip2_ob_in ;
input axi4s_dp_rdy_t kme_cceip3_ob_in ;
input axi4s_dp_rdy_t kme_cddip0_ob_in ;
input axi4s_dp_rdy_t kme_cddip1_ob_in ;
input axi4s_dp_rdy_t kme_cddip2_ob_in ;
input axi4s_dp_rdy_t kme_cddip3_ob_in ;
input wire logic [63 : 0] ckv_dout ;
input wire logic ckv_mbe ;
input kim_entry_t kim_dout ;
input wire logic kim_mbe ;
input wire logic bimc_rst_n ;
input wire logic cceip_encrypt_bimc_isync ;
input wire logic cceip_encrypt_bimc_idat ;
input wire logic cceip_validate_bimc_isync ;
input wire logic cceip_validate_bimc_idat ;
input wire logic cddip_decrypt_bimc_isync ;
input wire logic cddip_decrypt_bimc_idat ;
input wire logic axi_bimc_isync ;
input wire logic axi_bimc_idat ;
input label_t[7 : 0] labels ;
input wire logic seed0_valid ;
input wire logic [255 : 0] seed0_internal_state_key ;
input wire logic [127 : 0] seed0_internal_state_value ;
input wire logic [47 : 0] seed0_reseed_interval ;
input wire logic seed1_valid ;
input wire logic [255 : 0] seed1_internal_state_key ;
input wire logic [127 : 0] seed1_internal_state_value ;
input wire logic [47 : 0] seed1_reseed_interval ;
input cr_kme_regfilePKG::tready_override_t tready_override ;
input cr_kme_regfilePKG::kop_fifo_override_t cceip_encrypt_kop_fifo_override ;
input cr_kme_regfilePKG::kop_fifo_override_t cceip_validate_kop_fifo_override ;
input cr_kme_regfilePKG::kop_fifo_override_t cddip_decrypt_kop_fifo_override ;
input wire logic [31 : 0] kdf_test_key_size ;
input wire logic kdf_test_mode_en ;
input cr_kme_regfilePKG::sa_global_ctrl_t sa_global_ctrl ;
input cr_kme_regfilePKG::sa_ctrl_t sa_ctrl[31 : 0] ;
endmodule
`end_keywords
/**portGenericDumpBegin KME_STUB axi4s_dp_rdy_t tready axi4s_dp_bus_t tvalid tlast tid tstrb tuser tdata DUMMY0 DUMMY1 kim_entry_t valid label_index ckv_length ckv_pointer pf_num vf_num vf_valid label_t guid_size label_size DUMMY3 delimiter_valid delimiter DUMMY4 DUMMY5 kme_ib_out kme_cceip0_ob_out kme_cceip1_ob_out kme_cceip2_ob_out kme_cceip3_ob_out kme_cddip0_ob_out kme_cddip1_ob_out kme_cddip2_ob_out kme_cddip3_ob_out ckv_rd ckv_addr kim_rd kim_addr cceip_encrypt_bimc_osync cceip_encrypt_bimc_odat cceip_encrypt_mbe cceip_validate_bimc_osync cceip_validate_bimc_odat cceip_validate_mbe cddip_decrypt_bimc_osync cddip_decrypt_bimc_odat cddip_decrypt_mbe axi_bimc_osync axi_bimc_odat axi_mbe seed0_invalidate seed1_invalidate set_txc_bp_int set_gcm_tag_fail_int set_key_tlv_miscmp_int set_tlv_bip2_error_int set_rsm_is_backpressuring idle_components sa_snapshot sa_count kme_idle clk rst_n scan_en scan_mode scan_rst_n disable_debug_cmd disable_unencrypted_keys suppress_key_tlvs always_validate_kim_ref kme_ib_in kme_cceip0_ob_in kme_cceip1_ob_in kme_cceip2_ob_in kme_cceip3_ob_in kme_cddip0_ob_in kme_cddip1_ob_in kme_cddip2_ob_in kme_cddip3_ob_in ckv_dout ckv_mbe kim_dout kim_mbe bimc_rst_n cceip_encrypt_bimc_isync cceip_encrypt_bimc_idat cceip_validate_bimc_isync cceip_validate_bimc_idat cddip_decrypt_bimc_isync cddip_decrypt_bimc_idat axi_bimc_isync axi_bimc_idat labels seed0_valid seed0_internal_state_key seed0_internal_state_value seed0_reseed_interval seed1_valid seed1_internal_state_key seed1_internal_state_value seed1_reseed_interval tready_override cceip_encrypt_kop_fifo_override cceip_validate_kop_fifo_override cddip_decrypt_kop_fifo_override kdf_test_key_size kdf_test_mode_en sa_global_ctrl sa_ctrl portGenericDumpEnd**/
/**ParamPreferVectorBegin ParamPreferVectorEnd**/
