`begin_keywords "1800-2012"
module cr_kme_regs_flops ( clk, i_reset_, i_sw_init, o_spare_config, o_cceip0_out_ia_wdata_part0, o_cceip0_out_ia_wdata_part1, o_cceip0_out_ia_wdata_part2, o_cceip0_out_ia_config, o_cceip0_out_im_config, o_cceip0_out_im_read_done, o_cceip1_out_ia_wdata_part0, o_cceip1_out_ia_wdata_part1, o_cceip1_out_ia_wdata_part2, o_cceip1_out_ia_config, o_cceip1_out_im_config, o_cceip1_out_im_read_done, o_cceip2_out_ia_wdata_part0, o_cceip2_out_ia_wdata_part1, o_cceip2_out_ia_wdata_part2, o_cceip2_out_ia_config, o_cceip2_out_im_config, o_cceip2_out_im_read_done, o_cceip3_out_ia_wdata_part0, o_cceip3_out_ia_wdata_part1, o_cceip3_out_ia_wdata_part2, o_cceip3_out_ia_config, o_cceip3_out_im_config, o_cceip3_out_im_read_done, o_cddip0_out_ia_wdata_part0, o_cddip0_out_ia_wdata_part1, o_cddip0_out_ia_wdata_part2, o_cddip0_out_ia_config, o_cddip0_out_im_config, o_cddip0_out_im_read_done, o_cddip1_out_ia_wdata_part0, o_cddip1_out_ia_wdata_part1, o_cddip1_out_ia_wdata_part2, o_cddip1_out_ia_config, o_cddip1_out_im_config, o_cddip1_out_im_read_done, o_cddip2_out_ia_wdata_part0, o_cddip2_out_ia_wdata_part1, o_cddip2_out_ia_wdata_part2, o_cddip2_out_ia_config, o_cddip2_out_im_config, o_cddip2_out_im_read_done, o_cddip3_out_ia_wdata_part0, o_cddip3_out_ia_wdata_part1, o_cddip3_out_ia_wdata_part2, o_cddip3_out_ia_config, o_cddip3_out_im_config, o_cddip3_out_im_read_done, o_ckv_ia_wdata_part0, o_ckv_ia_wdata_part1, o_ckv_ia_config, o_kim_ia_wdata_part0, o_kim_ia_wdata_part1, o_kim_ia_config, o_label0_config, o_label0_data7, o_label0_data6, o_label0_data5, o_label0_data4, o_label0_data3, o_label0_data2, o_label0_data1, o_label0_data0, o_label1_config, o_label1_data7, o_label1_data6, o_label1_data5, o_label1_data4, o_label1_data3, o_label1_data2, o_label1_data1, o_label1_data0, o_label2_config, o_label2_data7, o_label2_data6, o_label2_data5, o_label2_data4, o_label2_data3, o_label2_data2, o_label2_data1, o_label2_data0, o_label3_config, o_label3_data7, o_label3_data6, o_label3_data5, o_label3_data4, o_label3_data3, o_label3_data2, o_label3_data1, o_label3_data0, o_label4_config, o_label4_data7, o_label4_data6, o_label4_data5, o_label4_data4, o_label4_data3, o_label4_data2, o_label4_data1, o_label4_data0, o_label5_config, o_label5_data7, o_label5_data6, o_label5_data5, o_label5_data4, o_label5_data3, o_label5_data2, o_label5_data1, o_label5_data0, o_label6_config, o_label6_data7, o_label6_data6, o_label6_data5, o_label6_data4, o_label6_data3, o_label6_data2, o_label6_data1, o_label6_data0, o_label7_config, o_label7_data7, o_label7_data6, o_label7_data5, o_label7_data4, o_label7_data3, o_label7_data2, o_label7_data1, o_label7_data0, o_kdf_drbg_ctrl, o_kdf_drbg_seed_0_state_key_31_0, o_kdf_drbg_seed_0_state_key_63_32, o_kdf_drbg_seed_0_state_key_95_64, o_kdf_drbg_seed_0_state_key_127_96, o_kdf_drbg_seed_0_state_key_159_128, o_kdf_drbg_seed_0_state_key_191_160, o_kdf_drbg_seed_0_state_key_223_192, o_kdf_drbg_seed_0_state_key_255_224, o_kdf_drbg_seed_0_state_value_31_0, o_kdf_drbg_seed_0_state_value_63_32, o_kdf_drbg_seed_0_state_value_95_64, o_kdf_drbg_seed_0_state_value_127_96, o_kdf_drbg_seed_0_reseed_interval_0, o_kdf_drbg_seed_0_reseed_interval_1, o_kdf_drbg_seed_1_state_key_31_0, o_kdf_drbg_seed_1_state_key_63_32, o_kdf_drbg_seed_1_state_key_95_64, o_kdf_drbg_seed_1_state_key_127_96, o_kdf_drbg_seed_1_state_key_159_128, o_kdf_drbg_seed_1_state_key_191_160, o_kdf_drbg_seed_1_state_key_223_192, o_kdf_drbg_seed_1_state_key_255_224, o_kdf_drbg_seed_1_state_value_31_0, o_kdf_drbg_seed_1_state_value_63_32, o_kdf_drbg_seed_1_state_value_95_64, o_kdf_drbg_seed_1_state_value_127_96, o_kdf_drbg_seed_1_reseed_interval_0, o_kdf_drbg_seed_1_reseed_interval_1, o_interrupt_status, o_interrupt_mask, o_engine_sticky_status, o_bimc_monitor_mask, o_bimc_ecc_uncorrectable_error_cnt, o_bimc_ecc_correctable_error_cnt, o_bimc_parity_error_cnt, o_bimc_global_config, o_bimc_eccpar_debug, o_bimc_cmd2, o_bimc_cmd1, o_bimc_cmd0, o_bimc_rxcmd2, o_bimc_rxrsp2, o_bimc_pollrsp2, o_bimc_dbgcmd2, o_im_consumed, o_tready_override, o_regs_sa_ctrl, o_sa_snapshot_ia_wdata_part0, o_sa_snapshot_ia_wdata_part1, o_sa_snapshot_ia_config, o_sa_count_ia_wdata_part0, o_sa_count_ia_wdata_part1, o_sa_count_ia_config, o_cceip_encrypt_kop_fifo_override, o_cceip_validate_kop_fifo_override, o_cddip_decrypt_kop_fifo_override, o_sa_global_ctrl, o_sa_ctrl_ia_wdata_part0, o_sa_ctrl_ia_config, o_kdf_test_key_size_config, w_load_spare_config, w_load_cceip0_out_ia_wdata_part0, w_load_cceip0_out_ia_wdata_part1, w_load_cceip0_out_ia_wdata_part2, w_load_cceip0_out_ia_config, w_load_cceip0_out_im_config, w_load_cceip0_out_im_read_done, w_load_cceip1_out_ia_wdata_part0, w_load_cceip1_out_ia_wdata_part1, w_load_cceip1_out_ia_wdata_part2, w_load_cceip1_out_ia_config, w_load_cceip1_out_im_config, w_load_cceip1_out_im_read_done, w_load_cceip2_out_ia_wdata_part0, w_load_cceip2_out_ia_wdata_part1, w_load_cceip2_out_ia_wdata_part2, w_load_cceip2_out_ia_config, w_load_cceip2_out_im_config, w_load_cceip2_out_im_read_done, w_load_cceip3_out_ia_wdata_part0, w_load_cceip3_out_ia_wdata_part1, w_load_cceip3_out_ia_wdata_part2, w_load_cceip3_out_ia_config, w_load_cceip3_out_im_config, w_load_cceip3_out_im_read_done, w_load_cddip0_out_ia_wdata_part0, w_load_cddip0_out_ia_wdata_part1, w_load_cddip0_out_ia_wdata_part2, w_load_cddip0_out_ia_config, w_load_cddip0_out_im_config, w_load_cddip0_out_im_read_done, w_load_cddip1_out_ia_wdata_part0, w_load_cddip1_out_ia_wdata_part1, w_load_cddip1_out_ia_wdata_part2, w_load_cddip1_out_ia_config, w_load_cddip1_out_im_config, w_load_cddip1_out_im_read_done, w_load_cddip2_out_ia_wdata_part0, w_load_cddip2_out_ia_wdata_part1, w_load_cddip2_out_ia_wdata_part2, w_load_cddip2_out_ia_config, w_load_cddip2_out_im_config, w_load_cddip2_out_im_read_done, w_load_cddip3_out_ia_wdata_part0, w_load_cddip3_out_ia_wdata_part1, w_load_cddip3_out_ia_wdata_part2, w_load_cddip3_out_ia_config, w_load_cddip3_out_im_config, w_load_cddip3_out_im_read_done, w_load_ckv_ia_wdata_part0, w_load_ckv_ia_wdata_part1, w_load_ckv_ia_config, w_load_kim_ia_wdata_part0, w_load_kim_ia_wdata_part1, w_load_kim_ia_config, w_load_label0_config, w_load_label0_data7, w_load_label0_data6, w_load_label0_data5, w_load_label0_data4, w_load_label0_data3, w_load_label0_data2, w_load_label0_data1, w_load_label0_data0, w_load_label1_config, w_load_label1_data7, w_load_label1_data6, w_load_label1_data5, w_load_label1_data4, w_load_label1_data3, w_load_label1_data2, w_load_label1_data1, w_load_label1_data0, w_load_label2_config, w_load_label2_data7, w_load_label2_data6, w_load_label2_data5, w_load_label2_data4, w_load_label2_data3, w_load_label2_data2, w_load_label2_data1, w_load_label2_data0, w_load_label3_config, w_load_label3_data7, w_load_label3_data6, w_load_label3_data5, w_load_label3_data4, w_load_label3_data3, w_load_label3_data2, w_load_label3_data1, w_load_label3_data0, w_load_label4_config, w_load_label4_data7, w_load_label4_data6, w_load_label4_data5, w_load_label4_data4, w_load_label4_data3, w_load_label4_data2, w_load_label4_data1, w_load_label4_data0, w_load_label5_config, w_load_label5_data7, w_load_label5_data6, w_load_label5_data5, w_load_label5_data4, w_load_label5_data3, w_load_label5_data2, w_load_label5_data1, w_load_label5_data0, w_load_label6_config, w_load_label6_data7, w_load_label6_data6, w_load_label6_data5, w_load_label6_data4, w_load_label6_data3, w_load_label6_data2, w_load_label6_data1, w_load_label6_data0, w_load_label7_config, w_load_label7_data7, w_load_label7_data6, w_load_label7_data5, w_load_label7_data4, w_load_label7_data3, w_load_label7_data2, w_load_label7_data1, w_load_label7_data0, w_load_kdf_drbg_ctrl, w_load_kdf_drbg_seed_0_state_key_31_0, w_load_kdf_drbg_seed_0_state_key_63_32, w_load_kdf_drbg_seed_0_state_key_95_64, w_load_kdf_drbg_seed_0_state_key_127_96, w_load_kdf_drbg_seed_0_state_key_159_128, w_load_kdf_drbg_seed_0_state_key_191_160, w_load_kdf_drbg_seed_0_state_key_223_192, w_load_kdf_drbg_seed_0_state_key_255_224, w_load_kdf_drbg_seed_0_state_value_31_0, w_load_kdf_drbg_seed_0_state_value_63_32, w_load_kdf_drbg_seed_0_state_value_95_64, w_load_kdf_drbg_seed_0_state_value_127_96, w_load_kdf_drbg_seed_0_reseed_interval_0, w_load_kdf_drbg_seed_0_reseed_interval_1, w_load_kdf_drbg_seed_1_state_key_31_0, w_load_kdf_drbg_seed_1_state_key_63_32, w_load_kdf_drbg_seed_1_state_key_95_64, w_load_kdf_drbg_seed_1_state_key_127_96, w_load_kdf_drbg_seed_1_state_key_159_128, w_load_kdf_drbg_seed_1_state_key_191_160, w_load_kdf_drbg_seed_1_state_key_223_192, w_load_kdf_drbg_seed_1_state_key_255_224, w_load_kdf_drbg_seed_1_state_value_31_0, w_load_kdf_drbg_seed_1_state_value_63_32, w_load_kdf_drbg_seed_1_state_value_95_64, w_load_kdf_drbg_seed_1_state_value_127_96, w_load_kdf_drbg_seed_1_reseed_interval_0, w_load_kdf_drbg_seed_1_reseed_interval_1, w_load_interrupt_status, w_load_interrupt_mask, w_load_engine_sticky_status, w_load_bimc_monitor_mask, w_load_bimc_ecc_uncorrectable_error_cnt, w_load_bimc_ecc_correctable_error_cnt, w_load_bimc_parity_error_cnt, w_load_bimc_global_config, w_load_bimc_eccpar_debug, w_load_bimc_cmd2, w_load_bimc_cmd1, w_load_bimc_cmd0, w_load_bimc_rxcmd2, w_load_bimc_rxrsp2, w_load_bimc_pollrsp2, w_load_bimc_dbgcmd2, w_load_im_consumed, w_load_tready_override, w_load_regs_sa_ctrl, w_load_sa_snapshot_ia_wdata_part0, w_load_sa_snapshot_ia_wdata_part1, w_load_sa_snapshot_ia_config, w_load_sa_count_ia_wdata_part0, w_load_sa_count_ia_wdata_part1, w_load_sa_count_ia_config, w_load_cceip_encrypt_kop_fifo_override, w_load_cceip_validate_kop_fifo_override, w_load_cddip_decrypt_kop_fifo_override, w_load_sa_global_ctrl, w_load_sa_ctrl_ia_wdata_part0, w_load_sa_ctrl_ia_config, w_load_kdf_test_key_size_config, f32_data );
input wire logic clk ;
input wire logic i_reset_ ;
input wire logic i_sw_init ;
output logic [31 : 0] o_spare_config ;
output logic [31 : 0] o_cceip0_out_ia_wdata_part0 ;
output logic [31 : 0] o_cceip0_out_ia_wdata_part1 ;
output logic [31 : 0] o_cceip0_out_ia_wdata_part2 ;
output logic [12 : 0] o_cceip0_out_ia_config ;
output logic [11 : 0] o_cceip0_out_im_config ;
output logic [1 : 0] o_cceip0_out_im_read_done ;
output logic [31 : 0] o_cceip1_out_ia_wdata_part0 ;
output logic [31 : 0] o_cceip1_out_ia_wdata_part1 ;
output logic [31 : 0] o_cceip1_out_ia_wdata_part2 ;
output logic [12 : 0] o_cceip1_out_ia_config ;
output logic [11 : 0] o_cceip1_out_im_config ;
output logic [1 : 0] o_cceip1_out_im_read_done ;
output logic [31 : 0] o_cceip2_out_ia_wdata_part0 ;
output logic [31 : 0] o_cceip2_out_ia_wdata_part1 ;
output logic [31 : 0] o_cceip2_out_ia_wdata_part2 ;
output logic [12 : 0] o_cceip2_out_ia_config ;
output logic [11 : 0] o_cceip2_out_im_config ;
output logic [1 : 0] o_cceip2_out_im_read_done ;
output logic [31 : 0] o_cceip3_out_ia_wdata_part0 ;
output logic [31 : 0] o_cceip3_out_ia_wdata_part1 ;
output logic [31 : 0] o_cceip3_out_ia_wdata_part2 ;
output logic [12 : 0] o_cceip3_out_ia_config ;
output logic [11 : 0] o_cceip3_out_im_config ;
output logic [1 : 0] o_cceip3_out_im_read_done ;
output logic [31 : 0] o_cddip0_out_ia_wdata_part0 ;
output logic [31 : 0] o_cddip0_out_ia_wdata_part1 ;
output logic [31 : 0] o_cddip0_out_ia_wdata_part2 ;
output logic [12 : 0] o_cddip0_out_ia_config ;
output logic [11 : 0] o_cddip0_out_im_config ;
output logic [1 : 0] o_cddip0_out_im_read_done ;
output logic [31 : 0] o_cddip1_out_ia_wdata_part0 ;
output logic [31 : 0] o_cddip1_out_ia_wdata_part1 ;
output logic [31 : 0] o_cddip1_out_ia_wdata_part2 ;
output logic [12 : 0] o_cddip1_out_ia_config ;
output logic [11 : 0] o_cddip1_out_im_config ;
output logic [1 : 0] o_cddip1_out_im_read_done ;
output logic [31 : 0] o_cddip2_out_ia_wdata_part0 ;
output logic [31 : 0] o_cddip2_out_ia_wdata_part1 ;
output logic [31 : 0] o_cddip2_out_ia_wdata_part2 ;
output logic [12 : 0] o_cddip2_out_ia_config ;
output logic [11 : 0] o_cddip2_out_im_config ;
output logic [1 : 0] o_cddip2_out_im_read_done ;
output logic [31 : 0] o_cddip3_out_ia_wdata_part0 ;
output logic [31 : 0] o_cddip3_out_ia_wdata_part1 ;
output logic [31 : 0] o_cddip3_out_ia_wdata_part2 ;
output logic [12 : 0] o_cddip3_out_ia_config ;
output logic [11 : 0] o_cddip3_out_im_config ;
output logic [1 : 0] o_cddip3_out_im_read_done ;
output logic [31 : 0] o_ckv_ia_wdata_part0 ;
output logic [31 : 0] o_ckv_ia_wdata_part1 ;
output logic [18 : 0] o_ckv_ia_config ;
output logic [20 : 0] o_kim_ia_wdata_part0 ;
output logic [16 : 0] o_kim_ia_wdata_part1 ;
output logic [17 : 0] o_kim_ia_config ;
output logic [15 : 0] o_label0_config ;
output logic [31 : 0] o_label0_data7 ;
output logic [31 : 0] o_label0_data6 ;
output logic [31 : 0] o_label0_data5 ;
output logic [31 : 0] o_label0_data4 ;
output logic [31 : 0] o_label0_data3 ;
output logic [31 : 0] o_label0_data2 ;
output logic [31 : 0] o_label0_data1 ;
output logic [31 : 0] o_label0_data0 ;
output logic [15 : 0] o_label1_config ;
output logic [31 : 0] o_label1_data7 ;
output logic [31 : 0] o_label1_data6 ;
output logic [31 : 0] o_label1_data5 ;
output logic [31 : 0] o_label1_data4 ;
output logic [31 : 0] o_label1_data3 ;
output logic [31 : 0] o_label1_data2 ;
output logic [31 : 0] o_label1_data1 ;
output logic [31 : 0] o_label1_data0 ;
output logic [15 : 0] o_label2_config ;
output logic [31 : 0] o_label2_data7 ;
output logic [31 : 0] o_label2_data6 ;
output logic [31 : 0] o_label2_data5 ;
output logic [31 : 0] o_label2_data4 ;
output logic [31 : 0] o_label2_data3 ;
output logic [31 : 0] o_label2_data2 ;
output logic [31 : 0] o_label2_data1 ;
output logic [31 : 0] o_label2_data0 ;
output logic [15 : 0] o_label3_config ;
output logic [31 : 0] o_label3_data7 ;
output logic [31 : 0] o_label3_data6 ;
output logic [31 : 0] o_label3_data5 ;
output logic [31 : 0] o_label3_data4 ;
output logic [31 : 0] o_label3_data3 ;
output logic [31 : 0] o_label3_data2 ;
output logic [31 : 0] o_label3_data1 ;
output logic [31 : 0] o_label3_data0 ;
output logic [15 : 0] o_label4_config ;
output logic [31 : 0] o_label4_data7 ;
output logic [31 : 0] o_label4_data6 ;
output logic [31 : 0] o_label4_data5 ;
output logic [31 : 0] o_label4_data4 ;
output logic [31 : 0] o_label4_data3 ;
output logic [31 : 0] o_label4_data2 ;
output logic [31 : 0] o_label4_data1 ;
output logic [31 : 0] o_label4_data0 ;
output logic [15 : 0] o_label5_config ;
output logic [31 : 0] o_label5_data7 ;
output logic [31 : 0] o_label5_data6 ;
output logic [31 : 0] o_label5_data5 ;
output logic [31 : 0] o_label5_data4 ;
output logic [31 : 0] o_label5_data3 ;
output logic [31 : 0] o_label5_data2 ;
output logic [31 : 0] o_label5_data1 ;
output logic [31 : 0] o_label5_data0 ;
output logic [15 : 0] o_label6_config ;
output logic [31 : 0] o_label6_data7 ;
output logic [31 : 0] o_label6_data6 ;
output logic [31 : 0] o_label6_data5 ;
output logic [31 : 0] o_label6_data4 ;
output logic [31 : 0] o_label6_data3 ;
output logic [31 : 0] o_label6_data2 ;
output logic [31 : 0] o_label6_data1 ;
output logic [31 : 0] o_label6_data0 ;
output logic [15 : 0] o_label7_config ;
output logic [31 : 0] o_label7_data7 ;
output logic [31 : 0] o_label7_data6 ;
output logic [31 : 0] o_label7_data5 ;
output logic [31 : 0] o_label7_data4 ;
output logic [31 : 0] o_label7_data3 ;
output logic [31 : 0] o_label7_data2 ;
output logic [31 : 0] o_label7_data1 ;
output logic [31 : 0] o_label7_data0 ;
output logic [1 : 0] o_kdf_drbg_ctrl ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_31_0 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_63_32 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_95_64 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_127_96 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_159_128 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_191_160 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_223_192 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_key_255_224 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_value_31_0 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_value_63_32 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_value_95_64 ;
output logic [31 : 0] o_kdf_drbg_seed_0_state_value_127_96 ;
output logic [31 : 0] o_kdf_drbg_seed_0_reseed_interval_0 ;
output logic [15 : 0] o_kdf_drbg_seed_0_reseed_interval_1 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_31_0 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_63_32 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_95_64 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_127_96 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_159_128 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_191_160 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_223_192 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_key_255_224 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_value_31_0 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_value_63_32 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_value_95_64 ;
output logic [31 : 0] o_kdf_drbg_seed_1_state_value_127_96 ;
output logic [31 : 0] o_kdf_drbg_seed_1_reseed_interval_0 ;
output logic [15 : 0] o_kdf_drbg_seed_1_reseed_interval_1 ;
output logic [4 : 0] o_interrupt_status ;
output logic [4 : 0] o_interrupt_mask ;
output logic [7 : 0] o_engine_sticky_status ;
output logic [6 : 0] o_bimc_monitor_mask ;
output logic [31 : 0] o_bimc_ecc_uncorrectable_error_cnt ;
output logic [31 : 0] o_bimc_ecc_correctable_error_cnt ;
output logic [31 : 0] o_bimc_parity_error_cnt ;
output logic [31 : 0] o_bimc_global_config ;
output logic [28 : 0] o_bimc_eccpar_debug ;
output logic [10 : 0] o_bimc_cmd2 ;
output logic [31 : 0] o_bimc_cmd1 ;
output logic [31 : 0] o_bimc_cmd0 ;
output logic [9 : 0] o_bimc_rxcmd2 ;
output logic [9 : 0] o_bimc_rxrsp2 ;
output logic [9 : 0] o_bimc_pollrsp2 ;
output logic [9 : 0] o_bimc_dbgcmd2 ;
output logic [15 : 0] o_im_consumed ;
output logic [8 : 0] o_tready_override ;
output logic [31 : 0] o_regs_sa_ctrl ;
output logic [31 : 0] o_sa_snapshot_ia_wdata_part0 ;
output logic [31 : 0] o_sa_snapshot_ia_wdata_part1 ;
output logic [8 : 0] o_sa_snapshot_ia_config ;
output logic [31 : 0] o_sa_count_ia_wdata_part0 ;
output logic [31 : 0] o_sa_count_ia_wdata_part1 ;
output logic [8 : 0] o_sa_count_ia_config ;
output logic [6 : 0] o_cceip_encrypt_kop_fifo_override ;
output logic [6 : 0] o_cceip_validate_kop_fifo_override ;
output logic [6 : 0] o_cddip_decrypt_kop_fifo_override ;
output logic [31 : 0] o_sa_global_ctrl ;
output logic [31 : 0] o_sa_ctrl_ia_wdata_part0 ;
output logic [8 : 0] o_sa_ctrl_ia_config ;
output logic [31 : 0] o_kdf_test_key_size_config ;
input wire logic w_load_spare_config ;
input wire logic w_load_cceip0_out_ia_wdata_part0 ;
input wire logic w_load_cceip0_out_ia_wdata_part1 ;
input wire logic w_load_cceip0_out_ia_wdata_part2 ;
input wire logic w_load_cceip0_out_ia_config ;
input wire logic w_load_cceip0_out_im_config ;
input wire logic w_load_cceip0_out_im_read_done ;
input wire logic w_load_cceip1_out_ia_wdata_part0 ;
input wire logic w_load_cceip1_out_ia_wdata_part1 ;
input wire logic w_load_cceip1_out_ia_wdata_part2 ;
input wire logic w_load_cceip1_out_ia_config ;
input wire logic w_load_cceip1_out_im_config ;
input wire logic w_load_cceip1_out_im_read_done ;
input wire logic w_load_cceip2_out_ia_wdata_part0 ;
input wire logic w_load_cceip2_out_ia_wdata_part1 ;
input wire logic w_load_cceip2_out_ia_wdata_part2 ;
input wire logic w_load_cceip2_out_ia_config ;
input wire logic w_load_cceip2_out_im_config ;
input wire logic w_load_cceip2_out_im_read_done ;
input wire logic w_load_cceip3_out_ia_wdata_part0 ;
input wire logic w_load_cceip3_out_ia_wdata_part1 ;
input wire logic w_load_cceip3_out_ia_wdata_part2 ;
input wire logic w_load_cceip3_out_ia_config ;
input wire logic w_load_cceip3_out_im_config ;
input wire logic w_load_cceip3_out_im_read_done ;
input wire logic w_load_cddip0_out_ia_wdata_part0 ;
input wire logic w_load_cddip0_out_ia_wdata_part1 ;
input wire logic w_load_cddip0_out_ia_wdata_part2 ;
input wire logic w_load_cddip0_out_ia_config ;
input wire logic w_load_cddip0_out_im_config ;
input wire logic w_load_cddip0_out_im_read_done ;
input wire logic w_load_cddip1_out_ia_wdata_part0 ;
input wire logic w_load_cddip1_out_ia_wdata_part1 ;
input wire logic w_load_cddip1_out_ia_wdata_part2 ;
input wire logic w_load_cddip1_out_ia_config ;
input wire logic w_load_cddip1_out_im_config ;
input wire logic w_load_cddip1_out_im_read_done ;
input wire logic w_load_cddip2_out_ia_wdata_part0 ;
input wire logic w_load_cddip2_out_ia_wdata_part1 ;
input wire logic w_load_cddip2_out_ia_wdata_part2 ;
input wire logic w_load_cddip2_out_ia_config ;
input wire logic w_load_cddip2_out_im_config ;
input wire logic w_load_cddip2_out_im_read_done ;
input wire logic w_load_cddip3_out_ia_wdata_part0 ;
input wire logic w_load_cddip3_out_ia_wdata_part1 ;
input wire logic w_load_cddip3_out_ia_wdata_part2 ;
input wire logic w_load_cddip3_out_ia_config ;
input wire logic w_load_cddip3_out_im_config ;
input wire logic w_load_cddip3_out_im_read_done ;
input wire logic w_load_ckv_ia_wdata_part0 ;
input wire logic w_load_ckv_ia_wdata_part1 ;
input wire logic w_load_ckv_ia_config ;
input wire logic w_load_kim_ia_wdata_part0 ;
input wire logic w_load_kim_ia_wdata_part1 ;
input wire logic w_load_kim_ia_config ;
input wire logic w_load_label0_config ;
input wire logic w_load_label0_data7 ;
input wire logic w_load_label0_data6 ;
input wire logic w_load_label0_data5 ;
input wire logic w_load_label0_data4 ;
input wire logic w_load_label0_data3 ;
input wire logic w_load_label0_data2 ;
input wire logic w_load_label0_data1 ;
input wire logic w_load_label0_data0 ;
input wire logic w_load_label1_config ;
input wire logic w_load_label1_data7 ;
input wire logic w_load_label1_data6 ;
input wire logic w_load_label1_data5 ;
input wire logic w_load_label1_data4 ;
input wire logic w_load_label1_data3 ;
input wire logic w_load_label1_data2 ;
input wire logic w_load_label1_data1 ;
input wire logic w_load_label1_data0 ;
input wire logic w_load_label2_config ;
input wire logic w_load_label2_data7 ;
input wire logic w_load_label2_data6 ;
input wire logic w_load_label2_data5 ;
input wire logic w_load_label2_data4 ;
input wire logic w_load_label2_data3 ;
input wire logic w_load_label2_data2 ;
input wire logic w_load_label2_data1 ;
input wire logic w_load_label2_data0 ;
input wire logic w_load_label3_config ;
input wire logic w_load_label3_data7 ;
input wire logic w_load_label3_data6 ;
input wire logic w_load_label3_data5 ;
input wire logic w_load_label3_data4 ;
input wire logic w_load_label3_data3 ;
input wire logic w_load_label3_data2 ;
input wire logic w_load_label3_data1 ;
input wire logic w_load_label3_data0 ;
input wire logic w_load_label4_config ;
input wire logic w_load_label4_data7 ;
input wire logic w_load_label4_data6 ;
input wire logic w_load_label4_data5 ;
input wire logic w_load_label4_data4 ;
input wire logic w_load_label4_data3 ;
input wire logic w_load_label4_data2 ;
input wire logic w_load_label4_data1 ;
input wire logic w_load_label4_data0 ;
input wire logic w_load_label5_config ;
input wire logic w_load_label5_data7 ;
input wire logic w_load_label5_data6 ;
input wire logic w_load_label5_data5 ;
input wire logic w_load_label5_data4 ;
input wire logic w_load_label5_data3 ;
input wire logic w_load_label5_data2 ;
input wire logic w_load_label5_data1 ;
input wire logic w_load_label5_data0 ;
input wire logic w_load_label6_config ;
input wire logic w_load_label6_data7 ;
input wire logic w_load_label6_data6 ;
input wire logic w_load_label6_data5 ;
input wire logic w_load_label6_data4 ;
input wire logic w_load_label6_data3 ;
input wire logic w_load_label6_data2 ;
input wire logic w_load_label6_data1 ;
input wire logic w_load_label6_data0 ;
input wire logic w_load_label7_config ;
input wire logic w_load_label7_data7 ;
input wire logic w_load_label7_data6 ;
input wire logic w_load_label7_data5 ;
input wire logic w_load_label7_data4 ;
input wire logic w_load_label7_data3 ;
input wire logic w_load_label7_data2 ;
input wire logic w_load_label7_data1 ;
input wire logic w_load_label7_data0 ;
input wire logic w_load_kdf_drbg_ctrl ;
input wire logic w_load_kdf_drbg_seed_0_state_key_31_0 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_63_32 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_95_64 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_127_96 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_159_128 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_191_160 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_223_192 ;
input wire logic w_load_kdf_drbg_seed_0_state_key_255_224 ;
input wire logic w_load_kdf_drbg_seed_0_state_value_31_0 ;
input wire logic w_load_kdf_drbg_seed_0_state_value_63_32 ;
input wire logic w_load_kdf_drbg_seed_0_state_value_95_64 ;
input wire logic w_load_kdf_drbg_seed_0_state_value_127_96 ;
input wire logic w_load_kdf_drbg_seed_0_reseed_interval_0 ;
input wire logic w_load_kdf_drbg_seed_0_reseed_interval_1 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_31_0 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_63_32 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_95_64 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_127_96 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_159_128 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_191_160 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_223_192 ;
input wire logic w_load_kdf_drbg_seed_1_state_key_255_224 ;
input wire logic w_load_kdf_drbg_seed_1_state_value_31_0 ;
input wire logic w_load_kdf_drbg_seed_1_state_value_63_32 ;
input wire logic w_load_kdf_drbg_seed_1_state_value_95_64 ;
input wire logic w_load_kdf_drbg_seed_1_state_value_127_96 ;
input wire logic w_load_kdf_drbg_seed_1_reseed_interval_0 ;
input wire logic w_load_kdf_drbg_seed_1_reseed_interval_1 ;
input wire logic w_load_interrupt_status ;
input wire logic w_load_interrupt_mask ;
input wire logic w_load_engine_sticky_status ;
input wire logic w_load_bimc_monitor_mask ;
input wire logic w_load_bimc_ecc_uncorrectable_error_cnt ;
input wire logic w_load_bimc_ecc_correctable_error_cnt ;
input wire logic w_load_bimc_parity_error_cnt ;
input wire logic w_load_bimc_global_config ;
input wire logic w_load_bimc_eccpar_debug ;
input wire logic w_load_bimc_cmd2 ;
input wire logic w_load_bimc_cmd1 ;
input wire logic w_load_bimc_cmd0 ;
input wire logic w_load_bimc_rxcmd2 ;
input wire logic w_load_bimc_rxrsp2 ;
input wire logic w_load_bimc_pollrsp2 ;
input wire logic w_load_bimc_dbgcmd2 ;
input wire logic w_load_im_consumed ;
input wire logic w_load_tready_override ;
input wire logic w_load_regs_sa_ctrl ;
input wire logic w_load_sa_snapshot_ia_wdata_part0 ;
input wire logic w_load_sa_snapshot_ia_wdata_part1 ;
input wire logic w_load_sa_snapshot_ia_config ;
input wire logic w_load_sa_count_ia_wdata_part0 ;
input wire logic w_load_sa_count_ia_wdata_part1 ;
input wire logic w_load_sa_count_ia_config ;
input wire logic w_load_cceip_encrypt_kop_fifo_override ;
input wire logic w_load_cceip_validate_kop_fifo_override ;
input wire logic w_load_cddip_decrypt_kop_fifo_override ;
input wire logic w_load_sa_global_ctrl ;
input wire logic w_load_sa_ctrl_ia_wdata_part0 ;
input wire logic w_load_sa_ctrl_ia_config ;
input wire logic w_load_kdf_test_key_size_config ;
input wire logic [31 : 0] f32_data ;
endmodule
`end_keywords
/**portGenericDumpBegin clk i_reset_ i_sw_init o_spare_config o_cceip0_out_ia_wdata_part0 o_cceip0_out_ia_wdata_part1 o_cceip0_out_ia_wdata_part2 o_cceip0_out_ia_config o_cceip0_out_im_config o_cceip0_out_im_read_done o_cceip1_out_ia_wdata_part0 o_cceip1_out_ia_wdata_part1 o_cceip1_out_ia_wdata_part2 o_cceip1_out_ia_config o_cceip1_out_im_config o_cceip1_out_im_read_done o_cceip2_out_ia_wdata_part0 o_cceip2_out_ia_wdata_part1 o_cceip2_out_ia_wdata_part2 o_cceip2_out_ia_config o_cceip2_out_im_config o_cceip2_out_im_read_done o_cceip3_out_ia_wdata_part0 o_cceip3_out_ia_wdata_part1 o_cceip3_out_ia_wdata_part2 o_cceip3_out_ia_config o_cceip3_out_im_config o_cceip3_out_im_read_done o_cddip0_out_ia_wdata_part0 o_cddip0_out_ia_wdata_part1 o_cddip0_out_ia_wdata_part2 o_cddip0_out_ia_config o_cddip0_out_im_config o_cddip0_out_im_read_done o_cddip1_out_ia_wdata_part0 o_cddip1_out_ia_wdata_part1 o_cddip1_out_ia_wdata_part2 o_cddip1_out_ia_config o_cddip1_out_im_config o_cddip1_out_im_read_done o_cddip2_out_ia_wdata_part0 o_cddip2_out_ia_wdata_part1 o_cddip2_out_ia_wdata_part2 o_cddip2_out_ia_config o_cddip2_out_im_config o_cddip2_out_im_read_done o_cddip3_out_ia_wdata_part0 o_cddip3_out_ia_wdata_part1 o_cddip3_out_ia_wdata_part2 o_cddip3_out_ia_config o_cddip3_out_im_config o_cddip3_out_im_read_done o_ckv_ia_wdata_part0 o_ckv_ia_wdata_part1 o_ckv_ia_config o_kim_ia_wdata_part0 o_kim_ia_wdata_part1 o_kim_ia_config o_label0_config o_label0_data7 o_label0_data6 o_label0_data5 o_label0_data4 o_label0_data3 o_label0_data2 o_label0_data1 o_label0_data0 o_label1_config o_label1_data7 o_label1_data6 o_label1_data5 o_label1_data4 o_label1_data3 o_label1_data2 o_label1_data1 o_label1_data0 o_label2_config o_label2_data7 o_label2_data6 o_label2_data5 o_label2_data4 o_label2_data3 o_label2_data2 o_label2_data1 o_label2_data0 o_label3_config o_label3_data7 o_label3_data6 o_label3_data5 o_label3_data4 o_label3_data3 o_label3_data2 o_label3_data1 o_label3_data0 o_label4_config o_label4_data7 o_label4_data6 o_label4_data5 o_label4_data4 o_label4_data3 o_label4_data2 o_label4_data1 o_label4_data0 o_label5_config o_label5_data7 o_label5_data6 o_label5_data5 o_label5_data4 o_label5_data3 o_label5_data2 o_label5_data1 o_label5_data0 o_label6_config o_label6_data7 o_label6_data6 o_label6_data5 o_label6_data4 o_label6_data3 o_label6_data2 o_label6_data1 o_label6_data0 o_label7_config o_label7_data7 o_label7_data6 o_label7_data5 o_label7_data4 o_label7_data3 o_label7_data2 o_label7_data1 o_label7_data0 o_kdf_drbg_ctrl o_kdf_drbg_seed_0_state_key_31_0 o_kdf_drbg_seed_0_state_key_63_32 o_kdf_drbg_seed_0_state_key_95_64 o_kdf_drbg_seed_0_state_key_127_96 o_kdf_drbg_seed_0_state_key_159_128 o_kdf_drbg_seed_0_state_key_191_160 o_kdf_drbg_seed_0_state_key_223_192 o_kdf_drbg_seed_0_state_key_255_224 o_kdf_drbg_seed_0_state_value_31_0 o_kdf_drbg_seed_0_state_value_63_32 o_kdf_drbg_seed_0_state_value_95_64 o_kdf_drbg_seed_0_state_value_127_96 o_kdf_drbg_seed_0_reseed_interval_0 o_kdf_drbg_seed_0_reseed_interval_1 o_kdf_drbg_seed_1_state_key_31_0 o_kdf_drbg_seed_1_state_key_63_32 o_kdf_drbg_seed_1_state_key_95_64 o_kdf_drbg_seed_1_state_key_127_96 o_kdf_drbg_seed_1_state_key_159_128 o_kdf_drbg_seed_1_state_key_191_160 o_kdf_drbg_seed_1_state_key_223_192 o_kdf_drbg_seed_1_state_key_255_224 o_kdf_drbg_seed_1_state_value_31_0 o_kdf_drbg_seed_1_state_value_63_32 o_kdf_drbg_seed_1_state_value_95_64 o_kdf_drbg_seed_1_state_value_127_96 o_kdf_drbg_seed_1_reseed_interval_0 o_kdf_drbg_seed_1_reseed_interval_1 o_interrupt_status o_interrupt_mask o_engine_sticky_status o_bimc_monitor_mask o_bimc_ecc_uncorrectable_error_cnt o_bimc_ecc_correctable_error_cnt o_bimc_parity_error_cnt o_bimc_global_config o_bimc_eccpar_debug o_bimc_cmd2 o_bimc_cmd1 o_bimc_cmd0 o_bimc_rxcmd2 o_bimc_rxrsp2 o_bimc_pollrsp2 o_bimc_dbgcmd2 o_im_consumed o_tready_override o_regs_sa_ctrl o_sa_snapshot_ia_wdata_part0 o_sa_snapshot_ia_wdata_part1 o_sa_snapshot_ia_config o_sa_count_ia_wdata_part0 o_sa_count_ia_wdata_part1 o_sa_count_ia_config o_cceip_encrypt_kop_fifo_override o_cceip_validate_kop_fifo_override o_cddip_decrypt_kop_fifo_override o_sa_global_ctrl o_sa_ctrl_ia_wdata_part0 o_sa_ctrl_ia_config o_kdf_test_key_size_config w_load_spare_config w_load_cceip0_out_ia_wdata_part0 w_load_cceip0_out_ia_wdata_part1 w_load_cceip0_out_ia_wdata_part2 w_load_cceip0_out_ia_config w_load_cceip0_out_im_config w_load_cceip0_out_im_read_done w_load_cceip1_out_ia_wdata_part0 w_load_cceip1_out_ia_wdata_part1 w_load_cceip1_out_ia_wdata_part2 w_load_cceip1_out_ia_config w_load_cceip1_out_im_config w_load_cceip1_out_im_read_done w_load_cceip2_out_ia_wdata_part0 w_load_cceip2_out_ia_wdata_part1 w_load_cceip2_out_ia_wdata_part2 w_load_cceip2_out_ia_config w_load_cceip2_out_im_config w_load_cceip2_out_im_read_done w_load_cceip3_out_ia_wdata_part0 w_load_cceip3_out_ia_wdata_part1 w_load_cceip3_out_ia_wdata_part2 w_load_cceip3_out_ia_config w_load_cceip3_out_im_config w_load_cceip3_out_im_read_done w_load_cddip0_out_ia_wdata_part0 w_load_cddip0_out_ia_wdata_part1 w_load_cddip0_out_ia_wdata_part2 w_load_cddip0_out_ia_config w_load_cddip0_out_im_config w_load_cddip0_out_im_read_done w_load_cddip1_out_ia_wdata_part0 w_load_cddip1_out_ia_wdata_part1 w_load_cddip1_out_ia_wdata_part2 w_load_cddip1_out_ia_config w_load_cddip1_out_im_config w_load_cddip1_out_im_read_done w_load_cddip2_out_ia_wdata_part0 w_load_cddip2_out_ia_wdata_part1 w_load_cddip2_out_ia_wdata_part2 w_load_cddip2_out_ia_config w_load_cddip2_out_im_config w_load_cddip2_out_im_read_done w_load_cddip3_out_ia_wdata_part0 w_load_cddip3_out_ia_wdata_part1 w_load_cddip3_out_ia_wdata_part2 w_load_cddip3_out_ia_config w_load_cddip3_out_im_config w_load_cddip3_out_im_read_done w_load_ckv_ia_wdata_part0 w_load_ckv_ia_wdata_part1 w_load_ckv_ia_config w_load_kim_ia_wdata_part0 w_load_kim_ia_wdata_part1 w_load_kim_ia_config w_load_label0_config w_load_label0_data7 w_load_label0_data6 w_load_label0_data5 w_load_label0_data4 w_load_label0_data3 w_load_label0_data2 w_load_label0_data1 w_load_label0_data0 w_load_label1_config w_load_label1_data7 w_load_label1_data6 w_load_label1_data5 w_load_label1_data4 w_load_label1_data3 w_load_label1_data2 w_load_label1_data1 w_load_label1_data0 w_load_label2_config w_load_label2_data7 w_load_label2_data6 w_load_label2_data5 w_load_label2_data4 w_load_label2_data3 w_load_label2_data2 w_load_label2_data1 w_load_label2_data0 w_load_label3_config w_load_label3_data7 w_load_label3_data6 w_load_label3_data5 w_load_label3_data4 w_load_label3_data3 w_load_label3_data2 w_load_label3_data1 w_load_label3_data0 w_load_label4_config w_load_label4_data7 w_load_label4_data6 w_load_label4_data5 w_load_label4_data4 w_load_label4_data3 w_load_label4_data2 w_load_label4_data1 w_load_label4_data0 w_load_label5_config w_load_label5_data7 w_load_label5_data6 w_load_label5_data5 w_load_label5_data4 w_load_label5_data3 w_load_label5_data2 w_load_label5_data1 w_load_label5_data0 w_load_label6_config w_load_label6_data7 w_load_label6_data6 w_load_label6_data5 w_load_label6_data4 w_load_label6_data3 w_load_label6_data2 w_load_label6_data1 w_load_label6_data0 w_load_label7_config w_load_label7_data7 w_load_label7_data6 w_load_label7_data5 w_load_label7_data4 w_load_label7_data3 w_load_label7_data2 w_load_label7_data1 w_load_label7_data0 w_load_kdf_drbg_ctrl w_load_kdf_drbg_seed_0_state_key_31_0 w_load_kdf_drbg_seed_0_state_key_63_32 w_load_kdf_drbg_seed_0_state_key_95_64 w_load_kdf_drbg_seed_0_state_key_127_96 w_load_kdf_drbg_seed_0_state_key_159_128 w_load_kdf_drbg_seed_0_state_key_191_160 w_load_kdf_drbg_seed_0_state_key_223_192 w_load_kdf_drbg_seed_0_state_key_255_224 w_load_kdf_drbg_seed_0_state_value_31_0 w_load_kdf_drbg_seed_0_state_value_63_32 w_load_kdf_drbg_seed_0_state_value_95_64 w_load_kdf_drbg_seed_0_state_value_127_96 w_load_kdf_drbg_seed_0_reseed_interval_0 w_load_kdf_drbg_seed_0_reseed_interval_1 w_load_kdf_drbg_seed_1_state_key_31_0 w_load_kdf_drbg_seed_1_state_key_63_32 w_load_kdf_drbg_seed_1_state_key_95_64 w_load_kdf_drbg_seed_1_state_key_127_96 w_load_kdf_drbg_seed_1_state_key_159_128 w_load_kdf_drbg_seed_1_state_key_191_160 w_load_kdf_drbg_seed_1_state_key_223_192 w_load_kdf_drbg_seed_1_state_key_255_224 w_load_kdf_drbg_seed_1_state_value_31_0 w_load_kdf_drbg_seed_1_state_value_63_32 w_load_kdf_drbg_seed_1_state_value_95_64 w_load_kdf_drbg_seed_1_state_value_127_96 w_load_kdf_drbg_seed_1_reseed_interval_0 w_load_kdf_drbg_seed_1_reseed_interval_1 w_load_interrupt_status w_load_interrupt_mask w_load_engine_sticky_status w_load_bimc_monitor_mask w_load_bimc_ecc_uncorrectable_error_cnt w_load_bimc_ecc_correctable_error_cnt w_load_bimc_parity_error_cnt w_load_bimc_global_config w_load_bimc_eccpar_debug w_load_bimc_cmd2 w_load_bimc_cmd1 w_load_bimc_cmd0 w_load_bimc_rxcmd2 w_load_bimc_rxrsp2 w_load_bimc_pollrsp2 w_load_bimc_dbgcmd2 w_load_im_consumed w_load_tready_override w_load_regs_sa_ctrl w_load_sa_snapshot_ia_wdata_part0 w_load_sa_snapshot_ia_wdata_part1 w_load_sa_snapshot_ia_config w_load_sa_count_ia_wdata_part0 w_load_sa_count_ia_wdata_part1 w_load_sa_count_ia_config w_load_cceip_encrypt_kop_fifo_override w_load_cceip_validate_kop_fifo_override w_load_cddip_decrypt_kop_fifo_override w_load_sa_global_ctrl w_load_sa_ctrl_ia_wdata_part0 w_load_sa_ctrl_ia_config w_load_kdf_test_key_size_config f32_data portGenericDumpEnd**/
/**ParamPreferVectorBegin ParamPreferVectorEnd**/
