`begin_keywords "1800-2012"
module cr_kme_regfile_glue ( ckv_cmnd_op, ckv_cmnd_addr, ckv_wr_dat, ckv_ia_capability, ckv_ia_rdata_part0, ckv_ia_rdata_part1, ckv_ia_status, kim_cmnd_op, kim_cmnd_addr, kim_wr_dat, kim_ia_capability, kim_ia_rdata_part0, kim_ia_rdata_part1, kim_ia_status, engine_sticky_status, disable_ckv_kim_ism_reads, send_kme_ib_beat, debug_kme_ib_tvalid, debug_kme_ib_tlast, debug_kme_ib_tid, debug_kme_ib_tstrb, debug_kme_ib_tuser, debug_kme_ib_tdata, kme_cceip0_ob_out, kme_cceip1_ob_out, kme_cceip2_ob_out, kme_cceip3_ob_out, kme_cddip0_ob_out, kme_cddip1_ob_out, kme_cddip2_ob_out, kme_cddip3_ob_out, cceip_encrypt_bimc_isync, cceip_encrypt_bimc_idat, cceip_validate_bimc_isync, cceip_validate_bimc_idat, cddip_decrypt_bimc_isync, cddip_decrypt_bimc_idat, axi_bimc_isync, axi_bimc_idat, axi_term_bimc_isync, axi_term_bimc_idat, clk, rst_n, ckv_stat_code, ckv_stat_datawords, ckv_stat_addr, ckv_capability_type, ckv_capability_lst, ckv_rd_dat, o_ckv_ia_config, o_ckv_ia_wdata_part0, o_ckv_ia_wdata_part1, kim_stat_code, kim_stat_datawords, kim_stat_addr, kim_capability_type, kim_capability_lst, kim_rd_dat, o_kim_ia_config, o_kim_ia_wdata_part0, o_kim_ia_wdata_part1, set_rsm_is_backpressuring, wr_stb, wr_data, reg_addr, o_engine_sticky_status, o_disable_ckv_kim_ism_reads, o_send_kme_ib_beat, cceip0_out_ia_wdata, debug_kme_ib_tready, tready_override, kme_cceip0_ob_out_post, kme_cceip1_ob_out_post, kme_cceip2_ob_out_post, kme_cceip3_ob_out_post, kme_cddip0_ob_out_post, kme_cddip1_ob_out_post, kme_cddip2_ob_out_post, kme_cddip3_ob_out_post, cddip3_ism_osync, cddip3_ism_odat, cceip_encrypt_bimc_osync, cceip_encrypt_bimc_odat, cceip_validate_bimc_osync, cceip_validate_bimc_odat, cddip_decrypt_bimc_osync, cddip_decrypt_bimc_odat, axi_bimc_osync, axi_bimc_odat );
typedef struct packed {logic tvalid ; logic tlast ; logic [0 : 0] tid ; logic [7 : 0] tstrb ; logic [7 : 0] tuser ; logic [63 : 0] tdata ;} axi4s_dp_bus_t ;
output wire logic [3 : 0] ckv_cmnd_op ;
output wire logic [14 : 0] ckv_cmnd_addr ;
output wire logic [63 : 0] ckv_wr_dat ;
output cr_kme_regfilePKG::ckv_ia_capability_t ckv_ia_capability ;
output wire logic [31 : 0] ckv_ia_rdata_part0 ;
output wire logic [31 : 0] ckv_ia_rdata_part1 ;
output cr_kme_regfilePKG::ckv_ia_status_t ckv_ia_status ;
output wire logic [3 : 0] kim_cmnd_op ;
output wire logic [13 : 0] kim_cmnd_addr ;
output wire logic [37 : 0] kim_wr_dat ;
output cr_kme_regfilePKG::kim_ia_capability_t kim_ia_capability ;
output wire logic [20 : 0] kim_ia_rdata_part0 ;
output wire logic [16 : 0] kim_ia_rdata_part1 ;
output cr_kme_regfilePKG::kim_ia_status_t kim_ia_status ;
output logic [7 : 0] engine_sticky_status ;
output logic disable_ckv_kim_ism_reads ;
output logic send_kme_ib_beat ;
output logic debug_kme_ib_tvalid ;
output logic debug_kme_ib_tlast ;
output logic [0 : 0] debug_kme_ib_tid ;
output logic [7 : 0] debug_kme_ib_tstrb ;
output logic [7 : 0] debug_kme_ib_tuser ;
output logic [63 : 0] debug_kme_ib_tdata ;
output axi4s_dp_bus_t kme_cceip0_ob_out ;
output axi4s_dp_bus_t kme_cceip1_ob_out ;
output axi4s_dp_bus_t kme_cceip2_ob_out ;
output axi4s_dp_bus_t kme_cceip3_ob_out ;
output axi4s_dp_bus_t kme_cddip0_ob_out ;
output axi4s_dp_bus_t kme_cddip1_ob_out ;
output axi4s_dp_bus_t kme_cddip2_ob_out ;
output axi4s_dp_bus_t kme_cddip3_ob_out ;
output wire logic cceip_encrypt_bimc_isync ;
output wire logic cceip_encrypt_bimc_idat ;
output wire logic cceip_validate_bimc_isync ;
output wire logic cceip_validate_bimc_idat ;
output wire logic cddip_decrypt_bimc_isync ;
output wire logic cddip_decrypt_bimc_idat ;
output wire logic axi_bimc_isync ;
output wire logic axi_bimc_idat ;
output wire logic axi_term_bimc_isync ;
output wire logic axi_term_bimc_idat ;
input wire logic clk ;
input wire logic rst_n ;
input wire logic [2 : 0] ckv_stat_code ;
input wire logic [4 : 0] ckv_stat_datawords ;
input wire logic [14 : 0] ckv_stat_addr ;
input wire logic [3 : 0] ckv_capability_type ;
input wire logic [15 : 0] ckv_capability_lst ;
input wire logic [63 : 0] ckv_rd_dat ;
input cr_kme_regfilePKG::ckv_ia_config_t o_ckv_ia_config ;
input wire logic [31 : 0] o_ckv_ia_wdata_part0 ;
input wire logic [31 : 0] o_ckv_ia_wdata_part1 ;
input wire logic [2 : 0] kim_stat_code ;
input wire logic [4 : 0] kim_stat_datawords ;
input wire logic [13 : 0] kim_stat_addr ;
input wire logic [3 : 0] kim_capability_type ;
input wire logic [15 : 0] kim_capability_lst ;
input wire logic [37 : 0] kim_rd_dat ;
input cr_kme_regfilePKG::kim_ia_config_t o_kim_ia_config ;
input wire logic [20 : 0] o_kim_ia_wdata_part0 ;
input wire logic [16 : 0] o_kim_ia_wdata_part1 ;
input wire logic [7 : 0] set_rsm_is_backpressuring ;
input wire logic wr_stb ;
input wire logic [31 : 0] wr_data ;
input wire logic [10 : 0] reg_addr ;
input wire logic [7 : 0] o_engine_sticky_status ;
input wire logic o_disable_ckv_kim_ism_reads ;
input wire logic o_send_kme_ib_beat ;
input cr_kme_regfilePKG::cceip0_out_t cceip0_out_ia_wdata ;
input wire logic debug_kme_ib_tready ;
input cr_kme_regfilePKG::tready_override_t tready_override ;
input axi4s_dp_bus_t kme_cceip0_ob_out_post ;
input axi4s_dp_bus_t kme_cceip1_ob_out_post ;
input axi4s_dp_bus_t kme_cceip2_ob_out_post ;
input axi4s_dp_bus_t kme_cceip3_ob_out_post ;
input axi4s_dp_bus_t kme_cddip0_ob_out_post ;
input axi4s_dp_bus_t kme_cddip1_ob_out_post ;
input axi4s_dp_bus_t kme_cddip2_ob_out_post ;
input axi4s_dp_bus_t kme_cddip3_ob_out_post ;
input wire logic cddip3_ism_osync ;
input wire logic cddip3_ism_odat ;
input wire logic cceip_encrypt_bimc_osync ;
input wire logic cceip_encrypt_bimc_odat ;
input wire logic cceip_validate_bimc_osync ;
input wire logic cceip_validate_bimc_odat ;
input wire logic cddip_decrypt_bimc_osync ;
input wire logic cddip_decrypt_bimc_odat ;
input wire logic axi_bimc_osync ;
input wire logic axi_bimc_odat ;
endmodule
`end_keywords
/**portGenericDumpBegin axi4s_dp_bus_t tvalid tlast tid tstrb tuser tdata ckv_cmnd_op ckv_cmnd_addr ckv_wr_dat ckv_ia_capability ckv_ia_rdata_part0 ckv_ia_rdata_part1 ckv_ia_status kim_cmnd_op kim_cmnd_addr kim_wr_dat kim_ia_capability kim_ia_rdata_part0 kim_ia_rdata_part1 kim_ia_status engine_sticky_status disable_ckv_kim_ism_reads send_kme_ib_beat debug_kme_ib_tvalid debug_kme_ib_tlast debug_kme_ib_tid debug_kme_ib_tstrb debug_kme_ib_tuser debug_kme_ib_tdata kme_cceip0_ob_out kme_cceip1_ob_out kme_cceip2_ob_out kme_cceip3_ob_out kme_cddip0_ob_out kme_cddip1_ob_out kme_cddip2_ob_out kme_cddip3_ob_out cceip_encrypt_bimc_isync cceip_encrypt_bimc_idat cceip_validate_bimc_isync cceip_validate_bimc_idat cddip_decrypt_bimc_isync cddip_decrypt_bimc_idat axi_bimc_isync axi_bimc_idat axi_term_bimc_isync axi_term_bimc_idat clk rst_n ckv_stat_code ckv_stat_datawords ckv_stat_addr ckv_capability_type ckv_capability_lst ckv_rd_dat o_ckv_ia_config o_ckv_ia_wdata_part0 o_ckv_ia_wdata_part1 kim_stat_code kim_stat_datawords kim_stat_addr kim_capability_type kim_capability_lst kim_rd_dat o_kim_ia_config o_kim_ia_wdata_part0 o_kim_ia_wdata_part1 set_rsm_is_backpressuring wr_stb wr_data reg_addr o_engine_sticky_status o_disable_ckv_kim_ism_reads o_send_kme_ib_beat cceip0_out_ia_wdata debug_kme_ib_tready tready_override kme_cceip0_ob_out_post kme_cceip1_ob_out_post kme_cceip2_ob_out_post kme_cceip3_ob_out_post kme_cddip0_ob_out_post kme_cddip1_ob_out_post kme_cddip2_ob_out_post kme_cddip3_ob_out_post cddip3_ism_osync cddip3_ism_odat cceip_encrypt_bimc_osync cceip_encrypt_bimc_odat cceip_validate_bimc_osync cceip_validate_bimc_odat cddip_decrypt_bimc_osync cddip_decrypt_bimc_odat axi_bimc_osync axi_bimc_odat portGenericDumpEnd**/
/**ParamPreferVectorBegin ParamPreferVectorEnd**/
