`begin_keywords "1800-2012"
module cr_kme_regfile ( suppress_key_tlvs, kme_interrupt, rbus_ring_o, kme_cceip0_ob_out, kme_cceip0_ob_in_mod, kme_cceip1_ob_out, kme_cceip1_ob_in_mod, kme_cceip2_ob_out, kme_cceip2_ob_in_mod, kme_cceip3_ob_out, kme_cceip3_ob_in_mod, kme_cddip0_ob_out, kme_cddip0_ob_in_mod, kme_cddip1_ob_out, kme_cddip1_ob_in_mod, kme_cddip2_ob_out, kme_cddip2_ob_in_mod, kme_cddip3_ob_out, kme_cddip3_ob_in_mod, ckv_dout, ckv_mbe, kim_dout, kim_mbe, bimc_rst_n, cceip_encrypt_bimc_isync, cceip_encrypt_bimc_idat, cceip_validate_bimc_isync, cceip_validate_bimc_idat, cddip_decrypt_bimc_isync, cddip_decrypt_bimc_idat, axi_bimc_isync, axi_bimc_idat, labels, seed0_valid, seed0_internal_state_key, seed0_internal_state_value, seed0_reseed_interval, seed1_valid, seed1_internal_state_key, seed1_internal_state_value, seed1_reseed_interval, tready_override, cceip_encrypt_kop_fifo_override, cceip_validate_kop_fifo_override, cddip_decrypt_kop_fifo_override, manual_txc, always_validate_kim_ref, kdf_test_mode_en, kdf_test_key_size, sa_global_ctrl, sa_ctrl, debug_kme_ib_tvalid, debug_kme_ib_tlast, debug_kme_ib_tid, debug_kme_ib_tstrb, debug_kme_ib_tuser, debug_kme_ib_tdata, clk, rst_n, ovstb, lvm, mlvm, rbus_ring_i, cfg_start_addr, cfg_end_addr, kme_cceip0_ob_out_pre, kme_cceip0_ob_in, kme_cceip1_ob_out_pre, kme_cceip1_ob_in, kme_cceip2_ob_out_pre, kme_cceip2_ob_in, kme_cceip3_ob_out_pre, kme_cceip3_ob_in, kme_cddip0_ob_out_pre, kme_cddip0_ob_in, kme_cddip1_ob_out_pre, kme_cddip1_ob_in, kme_cddip2_ob_out_pre, kme_cddip2_ob_in, kme_cddip3_ob_out_pre, kme_cddip3_ob_in, ckv_rd, ckv_addr, kim_rd, kim_addr, cceip_encrypt_bimc_osync, cceip_encrypt_bimc_odat, cceip_encrypt_mbe, cceip_validate_bimc_osync, cceip_validate_bimc_odat, cceip_validate_mbe, cddip_decrypt_bimc_osync, cddip_decrypt_bimc_odat, cddip_decrypt_mbe, axi_bimc_osync, axi_bimc_odat, axi_mbe, seed0_invalidate, seed1_invalidate, set_txc_bp_int, set_gcm_tag_fail_int, set_key_tlv_miscmp_int, set_tlv_bip2_error_int, set_rsm_is_backpressuring, idle_components, sa_snapshot, sa_count, debug_kme_ib_tready );
typedef struct packed {logic [15 : 0] addr ; logic wr_strb ; logic [31 : 0] wr_data ; logic rd_strb ; logic [31 : 0] rd_data ; logic ack ; logic err_ack ;} kme_rbus_ring_t ;
typedef struct packed {logic tvalid ; logic tlast ; logic [0 : 0] tid ; logic [7 : 0] tstrb ; logic [7 : 0] tuser ; logic [63 : 0] tdata ;} axi4s_dp_bus_t ;
typedef struct packed {logic tready ;} axi4s_dp_rdy_t ;
typedef struct packed {logic [0 : 0] valid ; logic [2 : 0] label_index ; logic [1 : 0] ckv_length ; logic [14 : 0] ckv_pointer ; logic [3 : 0] pf_num ; logic [11 : 0] vf_num ; logic [0 : 0] vf_valid ;} kim_entry_t ;
typedef struct packed {logic [0 : 0] guid_size ; logic [5 : 0] label_size ; logic [255 : 0] label ; logic [0 : 0] delimiter_valid ; logic [7 : 0] delimiter ;} label_t ;
output wire logic suppress_key_tlvs ;
output wire logic kme_interrupt ;
output kme_rbus_ring_t rbus_ring_o ;
output axi4s_dp_bus_t kme_cceip0_ob_out ;
output axi4s_dp_rdy_t kme_cceip0_ob_in_mod ;
output axi4s_dp_bus_t kme_cceip1_ob_out ;
output axi4s_dp_rdy_t kme_cceip1_ob_in_mod ;
output axi4s_dp_bus_t kme_cceip2_ob_out ;
output axi4s_dp_rdy_t kme_cceip2_ob_in_mod ;
output axi4s_dp_bus_t kme_cceip3_ob_out ;
output axi4s_dp_rdy_t kme_cceip3_ob_in_mod ;
output axi4s_dp_bus_t kme_cddip0_ob_out ;
output axi4s_dp_rdy_t kme_cddip0_ob_in_mod ;
output axi4s_dp_bus_t kme_cddip1_ob_out ;
output axi4s_dp_rdy_t kme_cddip1_ob_in_mod ;
output axi4s_dp_bus_t kme_cddip2_ob_out ;
output axi4s_dp_rdy_t kme_cddip2_ob_in_mod ;
output axi4s_dp_bus_t kme_cddip3_ob_out ;
output axi4s_dp_rdy_t kme_cddip3_ob_in_mod ;
output wire logic [63 : 0] ckv_dout ;
output wire logic ckv_mbe ;
output kim_entry_t kim_dout ;
output wire logic kim_mbe ;
output wire logic bimc_rst_n ;
output wire logic cceip_encrypt_bimc_isync ;
output wire logic cceip_encrypt_bimc_idat ;
output wire logic cceip_validate_bimc_isync ;
output wire logic cceip_validate_bimc_idat ;
output wire logic cddip_decrypt_bimc_isync ;
output wire logic cddip_decrypt_bimc_idat ;
output wire logic axi_bimc_isync ;
output wire logic axi_bimc_idat ;
output label_t[7 : 0] labels ;
output wire logic seed0_valid ;
output wire logic [255 : 0] seed0_internal_state_key ;
output wire logic [127 : 0] seed0_internal_state_value ;
output wire logic [47 : 0] seed0_reseed_interval ;
output wire logic seed1_valid ;
output wire logic [255 : 0] seed1_internal_state_key ;
output wire logic [127 : 0] seed1_internal_state_value ;
output wire logic [47 : 0] seed1_reseed_interval ;
output cr_kme_regfilePKG::tready_override_t tready_override ;
output cr_kme_regfilePKG::kop_fifo_override_t cceip_encrypt_kop_fifo_override ;
output cr_kme_regfilePKG::kop_fifo_override_t cceip_validate_kop_fifo_override ;
output cr_kme_regfilePKG::kop_fifo_override_t cddip_decrypt_kop_fifo_override ;
output wire logic manual_txc ;
output wire logic always_validate_kim_ref ;
output wire logic kdf_test_mode_en ;
output wire logic [31 : 0] kdf_test_key_size ;
output cr_kme_regfilePKG::sa_global_ctrl_t sa_global_ctrl ;
output cr_kme_regfilePKG::sa_ctrl_t sa_ctrl[31 : 0] ;
output wire logic debug_kme_ib_tvalid ;
output wire logic debug_kme_ib_tlast ;
output wire logic [0 : 0] debug_kme_ib_tid ;
output wire logic [7 : 0] debug_kme_ib_tstrb ;
output wire logic [7 : 0] debug_kme_ib_tuser ;
output wire logic [63 : 0] debug_kme_ib_tdata ;
input wire logic clk ;
input wire logic rst_n ;
input wire logic ovstb ;
input wire logic lvm ;
input wire logic mlvm ;
input kme_rbus_ring_t rbus_ring_i ;
input wire logic [15 : 0] cfg_start_addr ;
input wire logic [15 : 0] cfg_end_addr ;
input axi4s_dp_bus_t kme_cceip0_ob_out_pre ;
input axi4s_dp_rdy_t kme_cceip0_ob_in ;
input axi4s_dp_bus_t kme_cceip1_ob_out_pre ;
input axi4s_dp_rdy_t kme_cceip1_ob_in ;
input axi4s_dp_bus_t kme_cceip2_ob_out_pre ;
input axi4s_dp_rdy_t kme_cceip2_ob_in ;
input axi4s_dp_bus_t kme_cceip3_ob_out_pre ;
input axi4s_dp_rdy_t kme_cceip3_ob_in ;
input axi4s_dp_bus_t kme_cddip0_ob_out_pre ;
input axi4s_dp_rdy_t kme_cddip0_ob_in ;
input axi4s_dp_bus_t kme_cddip1_ob_out_pre ;
input axi4s_dp_rdy_t kme_cddip1_ob_in ;
input axi4s_dp_bus_t kme_cddip2_ob_out_pre ;
input axi4s_dp_rdy_t kme_cddip2_ob_in ;
input axi4s_dp_bus_t kme_cddip3_ob_out_pre ;
input axi4s_dp_rdy_t kme_cddip3_ob_in ;
input wire logic ckv_rd ;
input wire logic [14 : 0] ckv_addr ;
input wire logic kim_rd ;
input wire logic [13 : 0] kim_addr ;
input wire logic cceip_encrypt_bimc_osync ;
input wire logic cceip_encrypt_bimc_odat ;
input wire logic cceip_encrypt_mbe ;
input wire logic cceip_validate_bimc_osync ;
input wire logic cceip_validate_bimc_odat ;
input wire logic cceip_validate_mbe ;
input wire logic cddip_decrypt_bimc_osync ;
input wire logic cddip_decrypt_bimc_odat ;
input wire logic cddip_decrypt_mbe ;
input wire logic axi_bimc_osync ;
input wire logic axi_bimc_odat ;
input wire logic axi_mbe ;
input wire logic seed0_invalidate ;
input wire logic seed1_invalidate ;
input wire logic set_txc_bp_int ;
input wire logic set_gcm_tag_fail_int ;
input wire logic set_key_tlv_miscmp_int ;
input wire logic set_tlv_bip2_error_int ;
input wire logic [7 : 0] set_rsm_is_backpressuring ;
input cr_kme_regfilePKG::idle_t idle_components ;
input cr_kme_regfilePKG::sa_snapshot_t sa_snapshot[31 : 0] ;
input cr_kme_regfilePKG::sa_count_t sa_count[31 : 0] ;
input wire logic debug_kme_ib_tready ;
endmodule
`end_keywords
/**portGenericDumpBegin kme_rbus_ring_t addr wr_strb wr_data rd_strb rd_data ack err_ack axi4s_dp_bus_t tvalid tlast tid tstrb tuser tdata axi4s_dp_rdy_t tready kim_entry_t valid label_index ckv_length ckv_pointer pf_num vf_num vf_valid label_t guid_size label_size DUMMY1 delimiter_valid delimiter DUMMY2 DUMMY3 DUMMY4 DUMMY5 suppress_key_tlvs kme_interrupt rbus_ring_o kme_cceip0_ob_out kme_cceip0_ob_in_mod kme_cceip1_ob_out kme_cceip1_ob_in_mod kme_cceip2_ob_out kme_cceip2_ob_in_mod kme_cceip3_ob_out kme_cceip3_ob_in_mod kme_cddip0_ob_out kme_cddip0_ob_in_mod kme_cddip1_ob_out kme_cddip1_ob_in_mod kme_cddip2_ob_out kme_cddip2_ob_in_mod kme_cddip3_ob_out kme_cddip3_ob_in_mod ckv_dout ckv_mbe kim_dout kim_mbe bimc_rst_n cceip_encrypt_bimc_isync cceip_encrypt_bimc_idat cceip_validate_bimc_isync cceip_validate_bimc_idat cddip_decrypt_bimc_isync cddip_decrypt_bimc_idat axi_bimc_isync axi_bimc_idat labels seed0_valid seed0_internal_state_key seed0_internal_state_value seed0_reseed_interval seed1_valid seed1_internal_state_key seed1_internal_state_value seed1_reseed_interval tready_override cceip_encrypt_kop_fifo_override cceip_validate_kop_fifo_override cddip_decrypt_kop_fifo_override manual_txc always_validate_kim_ref kdf_test_mode_en kdf_test_key_size sa_global_ctrl sa_ctrl debug_kme_ib_tvalid debug_kme_ib_tlast debug_kme_ib_tid debug_kme_ib_tstrb debug_kme_ib_tuser debug_kme_ib_tdata clk rst_n ovstb lvm mlvm rbus_ring_i cfg_start_addr cfg_end_addr kme_cceip0_ob_out_pre kme_cceip0_ob_in kme_cceip1_ob_out_pre kme_cceip1_ob_in kme_cceip2_ob_out_pre kme_cceip2_ob_in kme_cceip3_ob_out_pre kme_cceip3_ob_in kme_cddip0_ob_out_pre kme_cddip0_ob_in kme_cddip1_ob_out_pre kme_cddip1_ob_in kme_cddip2_ob_out_pre kme_cddip2_ob_in kme_cddip3_ob_out_pre kme_cddip3_ob_in ckv_rd ckv_addr kim_rd kim_addr cceip_encrypt_bimc_osync cceip_encrypt_bimc_odat cceip_encrypt_mbe cceip_validate_bimc_osync cceip_validate_bimc_odat cceip_validate_mbe cddip_decrypt_bimc_osync cddip_decrypt_bimc_odat cddip_decrypt_mbe axi_bimc_osync axi_bimc_odat axi_mbe seed0_invalidate seed1_invalidate set_txc_bp_int set_gcm_tag_fail_int set_key_tlv_miscmp_int set_tlv_bip2_error_int set_rsm_is_backpressuring idle_components sa_snapshot sa_count debug_kme_ib_tready portGenericDumpEnd**/
/**ParamPreferVectorBegin ParamPreferVectorEnd**/
