
module cr_axi4s2_slv ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "673.000000"
cr_fifo_wrap2_xcm11 u_cr_fifo_wrap2 ();
ixc_assign _zz_strnp_12 ();
ixc_assign_83 _zz_strnp_11 ();
ixc_assign _zz_strnp_10 ();
ixc_assign _zz_strnp_9 ();
ixc_assign _zz_strnp_8 ();
ixc_assign_83 _zz_strnp_7 ();
ixc_assign _zz_strnp_6 ();
ixc_assign _zz_strnp_5 ();
ixc_assign _zz_strnp_4 ();
ixc_assign _zz_strnp_3 ();
ixc_assign _zz_strnp_2 ();
ixc_assign_83 _zz_strnp_1 ();
ixc_assign _zz_strnp_0 ();
endmodule
