
module cr_kme_guid_stitcher ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "556.000000"
cr_kme_fifo_xcm59 aux_cmd_fifo ();
ixc_assign _zz_strnp_9 ();
ixc_assign _zz_strnp_8 ();
ixc_assign_83 _zz_strnp_7 ();
ixc_assign_83 _zz_strnp_6 ();
ixc_assign _zz_strnp_5 ();
ixc_assign _zz_strnp_4 ();
ixc_assign_83 _zz_strnp_3 ();
ixc_assign _zz_strnp_2 ();
ixc_assign_64 _zz_strnp_1 ();
ixc_assign_64 _zz_strnp_0 ();
endmodule
