
module cr_tlvp2_rsm_core ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "3922.000000"
ixc_assign_64 _zz_strnp_0 ();
ixc_assign_2 _zz_strnp_1 ();
ixc_assign _zz_strnp_2 ();
ixc_assign _zz_strnp_4 ();
ixc_assign_8 _zz_strnp_5 ();
ixc_assign_8 _zz_strnp_6 ();
ixc_assign_64 _zz_strnp_7 ();
ixc_assign _zz_strnp_8 ();
ixc_assign _zz_strnp_9 ();
ixc_assign _zz_strnp_10 ();
ixc_assign_83 _zz_strnp_11 ();
ixc_assign _zz_strnp_3 ();
endmodule
