
module nx_fifo_ctrl_xcm39 ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "180.000000"
ixc_sample_logic_1_3 _zz_zy_sva_b2 ();
ixc_sample_logic_1_3 _zz_zy_sva_b1 ();
ixc_sample_logic_1_3 _zz_zy_sva_b0 ();
ixc_assign _zz_strnp_7 ();
ixc_assign _zz_strnp_6 ();
ixc_assign _zz_strnp_5 ();
ixc_assign _zz_strnp_4 ();
ixc_assign_2 _zz_strnp_3 ();
ixc_assign_2 _zz_strnp_2 ();
ixc_assign _zz_strnp_1 ();
ixc_assign _zz_strnp_0 ();
endmodule
