
module nx_rbus_ring ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "1929.000000"
ixc_assign_16 _zz_strnp_0 ();
ixc_assign _zz_strnp_1 ();
ixc_assign_32 _zz_strnp_2 ();
ixc_assign _zz_strnp_3 ();
ixc_assign_11 _zz_strnp_4 ();
ixc_assign _zz_strnp_5 ();
ixc_assign_32 _zz_strnp_6 ();
ixc_assign _zz_strnp_7 ();
ixc_assign_32 _zz_strnp_8 ();
ixc_assign _zz_strnp_9 ();
ixc_assign _zz_strnp_10 ();
endmodule
