
module nx_ram_1rw_xcm110 ;
//pragma CVASTRPROP MODULE SKELETON MODULEINFO "2336.000000"
ixc_assign _zz_strnp_10 ();
ixc_assign _zz_strnp_9 ();
ixc_assign _zz_strnp_8 ();
ixc_assign _zz_strnp_7 ();
ixc_assign _zz_strnp_6 ();
ixc_assign _zz_strnp_5 ();
ixc_assign _zz_strnp_4 ();
ixc_assign_96 \g._zz_strnp_0 ();
ixc_assign \g._zz_strnp_3 ();
ixc_assign \g._zz_strnp_2 ();
ixc_assign_96 \g._zz_strnp_1 ();
endmodule
