
## xeCompile starts at 03/19/2024 15:22:55 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 2890855, DISPLAY: sjcvl-ibarry:1
xeCompile compilePPC.qel
## 64bit program from /lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/bin on Linux 4.18.0-305.el8.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libhdl.so - 23H1_VXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_VXE, V23.03.131.s001            
#)libimp.so - 23H1_VXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_VXE, V23.03.131.s001            
#)libudq.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)liboptutil.so - 23H1_VXE, V23.03.131.s001            
#)libpich.so - 23H1_VXE, V23.03.131.s001            
#)libtich.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libsmDB.so - 23H1_VXE, V23.03.131.s001            
#)libtypedb.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)libhdldb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_VXE, V23.03.131.s001            
#)libcmp.so - 23H1_VXE, V23.03.131.s001            
#)libddb.so - 23H1_VXE, V23.03.131.s001            
#)libudp.so - 23H1_VXE, V23.03.131.s001            
#)libPDBCommands.so - 23H1_VXE, V23.03.131.s001            
#)libhwConfig.so - 23H1_VXE, V23.03.131.s001            
#)libCompilerRT.so - 23H1_VXE, V23.03.131.s001            
#)libclkBDD.so - 23H1_VXE, V23.03.131.s001            
#)libsdltm.so - 23H1_VXE, V23.03.131.s001            
#)libet3compile.so - 23H1_VXE, V23.03.131.s001            
#)libdb2util.so - 23H1_VXE, V23.03.131.s001            
#)liboptutil.so - 23H1_VXE, V23.03.131.s001            
#)libdb3.so - 23H1_VXE, V23.03.131.s001            
#)libet3wrapper.so - 23H1_VXE, V23.03.131.s001            
#)libsideFile.so - 23H1_VXE, V23.03.131.s001            
#)libdbgPrepare.so - 23H1_VXE, V23.03.131.s001            
#)libucdbwrt.so - 23H1_VXE, V23.03.131.s001            
#)libucdb_sh.so - 23H1_VXE, V23.03.131.s001            
#)libradb.so - 23H1_VXE, V23.03.131.s001            
#)libeclutil.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libdbgutil.so - 23H1_VXE, V23.03.131.s001            
#)libuxeenglic.so - 23H1_VXE, V23.03.131.s001            
#)libjsoncpp.so - 23H1_VXE, V23.03.131.s001            
#)libgenlics.a - 23H1_VXE, V23.03.131.s001            
#)libtcl.so - 23H1_VXE, V23.03.131.s001            
#)libtk.so - 23H1_VXE, V23.03.131.s001            
#)libtkdnd.so - 23H1_VXE, V23.03.131.s001            
#)libtix.so - 23H1_VXE, V23.03.131.s001            
#)libqt.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libsd.so - 23H1_VXE, V23.03.131.s001            
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3601275
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 96
  Name: Intel(R) Xeon(R) CPU E7-4830 v3 @ 2.10GHz
  Vendor: GenuineIntel, family: 6, model: 63, stepping: 4
  CPU min MHz: 1200.0000, BogoMIPS: 4200.28, virtualization: VT-x
  L1d cache: 32K, L1i cache: 32K, L2 cache: 256K, L3 cache: 30720K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007     1001        5        0        0      458
Swap (GB):      127        0      127
* Load info:
  1318 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              19.11 ( 20% CPU) |  16.78 ( 17% CPU) |  48.88 ( 51% CPU)
System info: hsv-sc49 - xeCompile - 2890855 2890845 - qtInit - 2024-03-19 15:22:55 - 19.11 20% 16.78 17% 48.88 51% - 1007 1001 5 458 127 0 127
000,000 s: XEC> design
000,000 s: INFO 53652: checking Palladium_Z1_Compile (23.00) ...

## oomr starts at 03/19/2024 15:22:56 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 2890995, DISPLAY: sjcvl-ibarry:1
oomr hdldb xcva_top
## 64bit program from /lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/bin on Linux 4.18.0-305.el8.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libimport.so - 23H1_VXE, V23.03.131.s001            
#)libmcp.so - 23H1_VXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libsmDB.so - 23H1_VXE, V23.03.131.s001            
#)libtypedb.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)libhdldb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libtcl.so - 23H1_VXE, V23.03.131.s001            
#)libqfsutil.so - 23H1_VXE, V23.03.131.s001            
#)libqfs.so - 23H1_VXE, V23.03.131.s001            
#)libnativeutils.so - 23H1_VXE, V23.03.131.s001            
#)libqt.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libsd.so - 23H1_VXE, V23.03.131.s001            
000,001 s: oomr - 23H1_VXE, V23.03.131.s001            
000,001 s: 
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3601275
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 96
  Name: Intel(R) Xeon(R) CPU E7-4830 v3 @ 2.10GHz
  Vendor: GenuineIntel, family: 6, model: 63, stepping: 4
  CPU min MHz: 1200.0000, BogoMIPS: 4200.28, virtualization: VT-x
  L1d cache: 32K, L1i cache: 32K, L2 cache: 256K, L3 cache: 30720K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007     1002        5        0        0      458
Swap (GB):      127        0      127
* Load info:
  1319 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              19.11 ( 20% CPU) |  16.78 ( 17% CPU) |  48.88 ( 51% CPU)
System info: hsv-sc49 - oomr - 2890995 2890855 - qtInit - 2024-03-19 15:22:56 - 19.11 20% 16.78 17% 48.88 51% - 1007 1002 5 458 127 0 127
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007     1002        5        0        0      458
Swap (GB):      127        0      127
* Load info:
  1319 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              19.11 ( 20% CPU) |  16.78 ( 17% CPU) |  48.88 ( 51% CPU)
System info: hsv-sc49 - oomr - 2890995 2890855 - qtExit - 2024-03-19 15:22:56 - 19.11 20% 16.78 17% 48.88 51% - 1007 1002 5 458 127 0 127
Peak usage info for oomr (pid 2890995, ppid 2890855) on hsv-sc49: CPU usage 0.00, Peak mem (Res 0 GB, Virt 1 GB), freePhyMem 5 GB, totalPhyMem 1007 GB, freeSwap 127 GB, totalSwap 128 GB
DRM memory info: hsv-sc49 - oomr - 2890995 - 2890855 - unknown unlimited
## oomr exits at 03/19/2024 15:22:56 Status: 0, PID: 2890995
000,001 s: WARNING (legacy-54241): The workstation was running low on memory (free memory dropped to 5 GB), therefore the performance might be impacted.
## oomr Elapsed time: 0:00:00, CPU time: 0:00:00.01, Memory Usage: 0.8G
## Child Proc. CPU time: 0:00:00.14
000,001 s: INFO (legacy-765432): ./AxisWork/xeCompile.args Path not found 
000,001 s: design Command: elapsed time 1 sec.
000,001 s: hdldb xcva_top
000,001 s: XEC> compile -etOnly -noDbgPrepare -seed 115188703 
000,001 s: INFO: Peak Memory Usage of the program (compile) is 1307  MB 
000,001 s: INFO (legacy-46435): Successfully generate memory rules file.
000,001 s: INFO (legacy-31228): Running core compile with ice mode

## et3compile starts at 03/19/2024 15:22:56 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 2890855, DISPLAY: sjcvl-ibarry:1
et3compile xcva_top -seed 115188703 -mode ice
000,001 s: et3compile xcva_top -seed 115188703 -mode ice <Version> V23.03.131.s001
000,001 s: 
000,001 s: INFO (qt2dadb-1035): ***COMPILING FOR IN-CIRCUIT EMULATION MODE***
000,001 s: WARNING (qt2dadb-1064): Using user defined database configuration file `/lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/etc/et3/et3compile.cfg'.
000,001 s: 	This overrides program-generated file `./dbFiles/et3compile.cfg'
000,001 s: MESSAGE (legacy-0): Executing command `xbatch xcva_top xcva_top'
000,002 s: Netlist optimizer initializing...
000,002 s: Palladium Z1 configuration detected.
000,002 s: Removing simple redundancies... 8493 boxes removed
000,002 s: Removing complex redundancies... 72  boxes removed
000,002 s: Relevelizing after breaking up 64, transforming 5070 and swapping 1723 muxes...
000,002 s: Saved 5070 logic boxes through muxes optimization
000,002 s: Running CBL module...
000,002 s: ---- ET5CBL: Parameters: -O2                          ---- 
000,002 s: ---- ET5CBL: Cleaning up database                     ---- 
000,002 s: ---- ET5CBL: Partitioning database into 4 parts       ---- 
000,003 s: ---- ET5CBL: Maximum 4 threads to run concurrently    ---- 
000,003 s: ---- ET5CBL: Converting database to netlists          ---- 
000,003 s: ---- ET5CBL: Clearing database                        ---- 
000,003 s: ---- ET5CBL: Thread 0: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 3: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 1: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 2: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 3: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 2: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 1: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 0: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 3: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 2: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 1: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 0: Checking iterator consistency  ---- 
000,004 s: ---- ET5CBL: Thread 1: Expanding LUTs into ANDs       ---- 
000,004 s: ---- ET5CBL: Thread 3: Expanding LUTs into ANDs       ---- 
000,004 s: ---- ET5CBL: Thread 2: Expanding LUTs into ANDs       ---- 
000,004 s: ---- ET5CBL: Thread 0: Expanding LUTs into ANDs       ---- 
000,004 s: ---- ET5CBL: Thread 0: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 1: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 0: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 1: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 2: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 2: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 3: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 3: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 1: Technology mapping             ---- 
000,004 s: ---- ET5CBL: Thread 0: Technology mapping             ---- 
000,004 s: ---- ET5CBL: Thread 0: Eliminating forcible gates     ---- 
000,004 s: ---- ET5CBL: Thread 1: Eliminating forcible gates     ---- 
000,004 s: ---- ET5CBL: Thread 0: Recreating final database      ---- 
000,004 s: ---- ET5CBL: Thread 1: Recreating final database      ---- 
000,004 s: ---- ET5CBL: Thread 0: Disposing netlist              ---- 
000,004 s: ---- ET5CBL: Thread 1: Disposing netlist              ---- 
000,004 s: ---- ET5CBL: Thread 2: Technology mapping             ---- 
000,004 s: ---- ET5CBL: Thread 3: Technology mapping             ---- 
000,004 s: ---- ET5CBL: Thread 2: Eliminating forcible gates     ---- 
000,004 s: ---- ET5CBL: Thread 2: Recreating final database      ---- 
000,004 s: ---- ET5CBL: Thread 2: Disposing netlist              ---- 
000,005 s: ---- ET5CBL: Thread 3: Eliminating forcible gates     ---- 
000,005 s: ---- ET5CBL: Thread 3: Recreating final database      ---- 
000,005 s: ---- ET5CBL: Thread 3: Disposing netlist              ---- 
000,005 s: ---- ET5CBL: Joined 4 optimization threads            ---- 
000,005 s: ---- ET5CBL: Merging DADB database                    ---- 
000,005 s: ---- ET5CBL: CBL Done                                 ---- 
000,005 s: Propagation round 1...
000,005 s: Propagating and accelerating 174496 primitives
000,005 s: ..
000,005 s: Propagation round 2...
000,005 s: Propagating and accelerating 173852 primitives
000,005 s: ..
000,005 s: Cleaning up...
000,005 s: Retiming...
000,005 s: Checking for redundant memory ports...
000,005 s: 0 ports removed
000,005 s: Removing complex redundancies... 0  boxes removed
000,005 s: Checking force nets ...
000,005 s: 0 buffer inserted
000,005 s: INFO (db2util-1073): DAS I/O 250 inputs
000,005 s: INFO (db2util-1074): DAS I/O 321 outputs
000,005 s: INFO (db2util-1071): Netlist optimization gives 36 % reduction.
000,005 s:  (234123 - 85806 = 148317)
000,005 s: INFO (db2util-1119): Available configuration: 1 domains
000,005 s: INFO (db2util-1113): The design contains 148317 ET primitives (boxes).
000,005 s: EDRAMS_PER_CHIP=48
000,005 s: ACTIVE_EDRAMS_PER_P512=8
000,005 s: Palladium Z1 configuration detected...
000,005 s: file_to_tvect: xc_work/mem_placement.constraints
000,005 s: Reading file 'xcva_top.mempreset'...
000,005 s: 
000,005 s: Collecting memory ports and instances...
000,005 s: 
000,005 s: Found 147 memory ports.
000,005 s: 
000,005 s: Found 92 memory instances.
000,005 s: WARNING (db2util-1059): Design contains 35 'DO_NOT_TOUCH' memory instances
000,005 s: 
000,005 s: Instruction usage: 11.2%
000,005 s: Finding mergeable memory (step 1)...
000,005 s: 
000,005 s: 
000,005 s: Finding mergeable memory (step 2)...
000,005 s: 
000,005 s: In total, 2 memory instances are candidates for at least 1 merger
000,005 s: 
000,005 s: 
000,005 s: In total, 2 memory instances were merged into 1 merger.
000,005 s: 
000,005 s: ....
000,005 s: Evaluated for compaction 91 memory instances.
000,005 s: Targeted 91 memory instances to INTRAM, 0 to EXTRAM.
000,005 s: Instruction usage after memory transformation: 11.3 %
000,005 s: INFO (db2util-1115): Compilation seed is 115188703
000,006 s: 
000,006 s:     Systems:     1 .
000,006 s:       Racks:     1 .
000,006 s: BrdClusters:     1 .
000,006 s:      Boards:     1 .
000,006 s:       Asics:     1 .
000,006 s:       P512s:     6 ......
000,006 s:        P64s:    48 ................................................
000,007 s: Reducing hop at epc level.
000,007 s: CPR round  1, maxlvl 101, path head  21055 lvl  85, tail  37977, len  38, m_is_marked   0, moved 15, NC 0 
000,007 s: CPR round  2, maxlvl  87, path head  38815 lvl  81, tail  37091, len  32, m_is_marked   0, moved 18, NC 0 
000,007 s: CPR round  3, maxlvl  84, path head  11614 lvl  80, tail  37977, len  30, m_is_marked   0, moved  5, NC 0 
000,007 s: CPR round  4, maxlvl  82, path head  64961 lvl  72, tail  36389, len  37, m_is_marked   0, moved 11, NC 0 
000,007 s: CPR round  5, maxlvl  80, path head 174006 lvl  79, tail  28732, len  50, m_is_marked   0, moved  5, NC 0 
000,007 s: CPR round  6, maxlvl  80, path head 174006 lvl  75, tail 155836, len  45, m_is_marked   0, moved  8, NC 1 
000,007 s: CPR round  7, maxlvl  78, path head 174003 lvl  78, tail  37091, len  49, m_is_marked   0, moved 19, NC 0 
000,007 s: CPR round  8, maxlvl  76, path head   3324 lvl  74, tail  37977, len  38, m_is_marked   0, moved  4, NC 0 
000,007 s: CPR round  9, maxlvl  75, path head  20189 lvl  73, tail 126727, len  50, m_is_marked   0, moved 13, NC 0 
000,007 s: CPR round 10, maxlvl  75, path head  11614 lvl  75, tail  37977, len  28, m_is_marked   0, moved  1, NC 1 
000,007 s: CPR round 11, maxlvl  75, path head  11614 lvl  75, tail  37977, len  30, m_is_marked   0, moved  2, NC 2 
000,007 s: CPR round 12, maxlvl  75, path head  11614 lvl  75, tail  37977, len  28, m_is_marked   0, moved  1, NC 3 
000,007 s: CPR round 13, maxlvl  75, path head  11614 lvl  74, tail  37977, len  28, m_is_marked   0, moved  1, NC 4 
000,007 s: CPR round 14, maxlvl  74, path head  21053 lvl  74, tail  33769, len  31, m_is_marked   0, moved 13, NC 0 
000,007 s: CPR round 15, maxlvl  74, path head  11614 lvl  74, tail  37977, len  29, m_is_marked   0, moved  0, NC 1 
000,007 s: CPR round 16, maxlvl  74, path head  11613 lvl  74, tail  37941, len  29, m_is_marked  25, moved  0, NC 1 
000,007 s: CPR round 17, maxlvl  74, path head  11611 lvl  74, tail  37973, len  29, m_is_marked  26, moved  0, NC 1 
000,007 s: Total relocated = 110
000,007 s: Maximum number of hops in all paths = 74
## et3compile exits at 03/19/2024 15:23:02 Status: 0, PID: 2890855
## et3compile Elapsed time: 0:00:06, CPU time: 0:00:09.18, Memory Usage: 1.9G
000,007 s: 0 115188703 -1 0 0
000,007 s: ^D
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007     1003        4        0        0      459
Swap (GB):      127        0      127
* Load info:
  1316 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              18.80 ( 20% CPU) |  16.79 ( 17% CPU) |  48.54 ( 51% CPU)
System info: hsv-sc49 - xeCompile - 2890855 2890845 - qtExit - 2024-03-19 15:23:02 - 18.80 20% 16.79 17% 48.54 51% - 1007 1003 4 459 127 0 127
Peak usage info for xeCompile (pid 2890855, ppid 2890845) on hsv-sc49: CPU usage 0.00, Peak mem (Res 0 GB, Virt 2 GB), freePhyMem 4 GB, totalPhyMem 1007 GB, freeSwap 127 GB, totalSwap 128 GB
000,007 s: WARNING (legacy-54241): The workstation was running low on memory (free memory dropped to 4 GB), therefore the performance might be impacted.
DRM memory info: hsv-sc49 - xeCompile - 2890855 - 2890845 - unknown unlimited
## xeCompile exits at 03/19/2024 15:23:02 Status: 0, PID: 2890855
## xeCompile Elapsed time: 0:00:07, CPU time: 0:00:09.29, Memory Usage: 1.9G
## Child Proc. CPU time: 0:00:00.33
