
## xeCompile starts at 05/20/2024 11:37:55 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 3891942, DISPLAY: sjcvl-ibarry:1
xeCompile compilePPC.qel
## 64bit program from /lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/bin on Linux 4.18.0-305.el8.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libhdl.so - 23H1_VXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_VXE, V23.03.131.s001            
#)libimp.so - 23H1_VXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_VXE, V23.03.131.s001            
#)libudq.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)liboptutil.so - 23H1_VXE, V23.03.131.s001            
#)libpich.so - 23H1_VXE, V23.03.131.s001            
#)libtich.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libsmDB.so - 23H1_VXE, V23.03.131.s001            
#)libtypedb.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)libhdldb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_VXE, V23.03.131.s001            
#)libcmp.so - 23H1_VXE, V23.03.131.s001            
#)libddb.so - 23H1_VXE, V23.03.131.s001            
#)libudp.so - 23H1_VXE, V23.03.131.s001            
#)libPDBCommands.so - 23H1_VXE, V23.03.131.s001            
#)libhwConfig.so - 23H1_VXE, V23.03.131.s001            
#)libCompilerRT.so - 23H1_VXE, V23.03.131.s001            
#)libclkBDD.so - 23H1_VXE, V23.03.131.s001            
#)libsdltm.so - 23H1_VXE, V23.03.131.s001            
#)libet3compile.so - 23H1_VXE, V23.03.131.s001            
#)libdb2util.so - 23H1_VXE, V23.03.131.s001            
#)liboptutil.so - 23H1_VXE, V23.03.131.s001            
#)libdb3.so - 23H1_VXE, V23.03.131.s001            
#)libet3wrapper.so - 23H1_VXE, V23.03.131.s001            
#)libsideFile.so - 23H1_VXE, V23.03.131.s001            
#)libdbgPrepare.so - 23H1_VXE, V23.03.131.s001            
#)libucdbwrt.so - 23H1_VXE, V23.03.131.s001            
#)libucdb_sh.so - 23H1_VXE, V23.03.131.s001            
#)libradb.so - 23H1_VXE, V23.03.131.s001            
#)libeclutil.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libdbgutil.so - 23H1_VXE, V23.03.131.s001            
#)libuxeenglic.so - 23H1_VXE, V23.03.131.s001            
#)libjsoncpp.so - 23H1_VXE, V23.03.131.s001            
#)libgenlics.a - 23H1_VXE, V23.03.131.s001            
#)libtcl.so - 23H1_VXE, V23.03.131.s001            
#)libtk.so - 23H1_VXE, V23.03.131.s001            
#)libtkdnd.so - 23H1_VXE, V23.03.131.s001            
#)libtix.so - 23H1_VXE, V23.03.131.s001            
#)libqt.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libsd.so - 23H1_VXE, V23.03.131.s001            
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3601275
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 96
  Name: Intel(R) Xeon(R) CPU E7-4830 v3 @ 2.10GHz
  Vendor: GenuineIntel, family: 6, model: 63, stepping: 4
  CPU min MHz: 1200.0000, BogoMIPS: 4200.28, virtualization: VT-x
  L1d cache: 32K, L1i cache: 32K, L2 cache: 256K, L3 cache: 30720K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007      443      563        0        0      200
Swap (GB):      127        1      126
* Load info:
  1415 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              10.53 ( 11% CPU) |   6.69 (  7% CPU) |   4.04 (  4% CPU)
System info: hsv-sc49 - xeCompile - 3891942 3891933 - qtInit - 2024-05-20 11:37:55 - 10.53 11% 6.69 7% 4.04 4% - 1007 443 563 200 127 1 126
000,000 s: XEC> design
000,000 s: INFO 53652: checking Palladium_Z1_Compile (23.00) ...

## oomr starts at 05/20/2024 11:37:56 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 3892150, DISPLAY: sjcvl-ibarry:1
oomr hdldb xcva_top
## 64bit program from /lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/bin on Linux 4.18.0-305.el8.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libimport.so - 23H1_VXE, V23.03.131.s001            
#)libmcp.so - 23H1_VXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libsmDB.so - 23H1_VXE, V23.03.131.s001            
#)libtypedb.so - 23H1_VXE, V23.03.131.s001            
#)libudqr.so - 23H1_VXE, V23.03.131.s001            
#)libhdldb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_VXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_VXE, V23.03.131.s001            
#)libdb.so - 23H1_VXE, V23.03.131.s001            
#)libtcl.so - 23H1_VXE, V23.03.131.s001            
#)libqfsutil.so - 23H1_VXE, V23.03.131.s001            
#)libqfs.so - 23H1_VXE, V23.03.131.s001            
#)libnativeutils.so - 23H1_VXE, V23.03.131.s001            
#)libqt.so - 23H1_VXE, V23.03.131.s001            
#)libqtutil.so - 23H1_VXE, V23.03.131.s001            
#)libsd.so - 23H1_VXE, V23.03.131.s001            
000,000 s: oomr - 23H1_VXE, V23.03.131.s001            
000,000 s: 
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3601275
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 96
  Name: Intel(R) Xeon(R) CPU E7-4830 v3 @ 2.10GHz
  Vendor: GenuineIntel, family: 6, model: 63, stepping: 4
  CPU min MHz: 1200.0000, BogoMIPS: 4200.28, virtualization: VT-x
  L1d cache: 32K, L1i cache: 32K, L2 cache: 256K, L3 cache: 30720K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007      444      563        0        0      200
Swap (GB):      127        1      126
* Load info:
  1421 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              10.53 ( 11% CPU) |   6.69 (  7% CPU) |   4.04 (  4% CPU)
System info: hsv-sc49 - oomr - 3892150 3891942 - qtInit - 2024-05-20 11:37:56 - 10.53 11% 6.69 7% 4.04 4% - 1007 444 563 200 127 1 126
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007      444      563        0        0      200
Swap (GB):      127        1      126
* Load info:
  1421 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              10.53 ( 11% CPU) |   6.69 (  7% CPU) |   4.04 (  4% CPU)
System info: hsv-sc49 - oomr - 3892150 3891942 - qtExit - 2024-05-20 11:37:56 - 10.53 11% 6.69 7% 4.04 4% - 1007 444 563 200 127 1 126
Peak usage info for oomr (pid 3892150, ppid 3891942) on hsv-sc49: CPU usage 0.00, Peak mem (Res 0 GB, Virt 1 GB), freePhyMem 563 GB, totalPhyMem 1007 GB, freeSwap 127 GB, totalSwap 128 GB
DRM memory info: hsv-sc49 - oomr - 3892150 - 3891942 - unknown unlimited
## oomr exits at 05/20/2024 11:37:56 Status: 0, PID: 3892150
## oomr Elapsed time: 0:00:00, CPU time: 0:00:00.01, Memory Usage: 0.8G
## Child Proc. CPU time: 0:00:00.13
000,000 s: INFO (legacy-765432): ./AxisWork/xeCompile.args Path not found 
000,000 s: design Command: elapsed time 0 sec.
000,000 s: hdldb xcva_top
000,000 s: XEC> compile -etOnly -noDbgPrepare -seed 262034294 
000,000 s: INFO: Peak Memory Usage of the program (compile) is 1307  MB 
000,000 s: INFO (legacy-46435): Successfully generate memory rules file.
000,000 s: INFO (legacy-31228): Running core compile with ice mode

## et3compile starts at 05/20/2024 11:37:56 ibarry V23.03.131.s001, HOST: hsv-sc49, PID: 3891942, DISPLAY: sjcvl-ibarry:1
et3compile xcva_top -seed 262034294 -mode ice
000,000 s: et3compile xcva_top -seed 262034294 -mode ice <Version> V23.03.131.s001
000,000 s: 
000,000 s: INFO (qt2dadb-1035): ***COMPILING FOR IN-CIRCUIT EMULATION MODE***
000,000 s: WARNING (qt2dadb-1064): Using user defined database configuration file `/lan/cva_rel/vxe23h1/23.03.131.s001/tools.lnx86/etc/et3/et3compile.cfg'.
000,000 s: 	This overrides program-generated file `./dbFiles/et3compile.cfg'
000,001 s: MESSAGE (legacy-0): Executing command `xbatch xcva_top xcva_top'
000,002 s: Netlist optimizer initializing...
000,002 s: Palladium Z1 configuration detected.
000,002 s: Removing simple redundancies... 33284 boxes removed
000,003 s: Removing complex redundancies... 72  boxes removed
000,003 s: Relevelizing after breaking up 148, transforming 14189 and swapping 3572 muxes...
000,003 s: Saved 14189 logic boxes through muxes optimization
000,003 s: Running CBL module...
000,003 s: ---- ET5CBL: Parameters: -O2                          ---- 
000,003 s: ---- ET5CBL: Cleaning up database                     ---- 
000,003 s: ---- ET5CBL: Partitioning database into 4 parts       ---- 
000,004 s: ---- ET5CBL: Maximum 4 threads to run concurrently    ---- 
000,004 s: ---- ET5CBL: Converting database to netlists          ---- 
000,005 s: ---- ET5CBL: Clearing database                        ---- 
000,006 s: ---- ET5CBL: Thread 0: Started                        ---- 
000,006 s: ---- ET5CBL: Thread 1: Started                        ---- 
000,006 s: ---- ET5CBL: Thread 2: Started                        ---- 
000,006 s: ---- ET5CBL: Thread 3: Started                        ---- 
000,006 s: ---- ET5CBL: Thread 3: Adding name listener           ---- 
000,006 s: ---- ET5CBL: Thread 3: Checking iterator consistency  ---- 
000,006 s: ---- ET5CBL: Thread 2: Adding name listener           ---- 
000,006 s: ---- ET5CBL: Thread 0: Adding name listener           ---- 
000,006 s: ---- ET5CBL: Thread 1: Adding name listener           ---- 
000,006 s: ---- ET5CBL: Thread 2: Checking iterator consistency  ---- 
000,006 s: ---- ET5CBL: Thread 1: Checking iterator consistency  ---- 
000,006 s: ---- ET5CBL: Thread 0: Checking iterator consistency  ---- 
000,006 s: ---- ET5CBL: Thread 3: Expanding LUTs into ANDs       ---- 
000,006 s: ---- ET5CBL: Thread 1: Expanding LUTs into ANDs       ---- 
000,006 s: ---- ET5CBL: Thread 2: Expanding LUTs into ANDs       ---- 
000,006 s: ---- ET5CBL: Thread 0: Expanding LUTs into ANDs       ---- 
000,006 s: ---- ET5CBL: Thread 3: Removing redundant logic       ---- 
000,006 s: ---- ET5CBL: Thread 1: Removing redundant logic       ---- 
000,006 s: ---- ET5CBL: Thread 0: Removing redundant logic       ---- 
000,006 s: ---- ET5CBL: Thread 3: Rewriting DAG-aware netlist    ---- 
000,006 s: ---- ET5CBL: Thread 1: Rewriting DAG-aware netlist    ---- 
000,006 s: ---- ET5CBL: Thread 2: Removing redundant logic       ---- 
000,006 s: ---- ET5CBL: Thread 0: Rewriting DAG-aware netlist    ---- 
000,006 s: ---- ET5CBL: Thread 2: Rewriting DAG-aware netlist    ---- 
000,007 s: ---- ET5CBL: Thread 1: Technology mapping             ---- 
000,007 s: ---- ET5CBL: Thread 0: Technology mapping             ---- 
000,007 s: ---- ET5CBL: Thread 3: Technology mapping             ---- 
000,008 s: ---- ET5CBL: Thread 1: Eliminating forcible gates     ---- 
000,008 s: ---- ET5CBL: Thread 0: Eliminating forcible gates     ---- 
000,008 s: ---- ET5CBL: Thread 0: Recreating final database      ---- 
000,008 s: ---- ET5CBL: Thread 2: Technology mapping             ---- 
000,008 s: ---- ET5CBL: Thread 0: Disposing netlist              ---- 
000,008 s: ---- ET5CBL: Thread 1: Recreating final database      ---- 
000,008 s: ---- ET5CBL: Thread 3: Eliminating forcible gates     ---- 
000,008 s: ---- ET5CBL: Thread 1: Disposing netlist              ---- 
000,008 s: ---- ET5CBL: Thread 2: Eliminating forcible gates     ---- 
000,008 s: ---- ET5CBL: Thread 2: Recreating final database      ---- 
000,009 s: ---- ET5CBL: Thread 2: Disposing netlist              ---- 
000,009 s: ---- ET5CBL: Thread 3: Recreating final database      ---- 
000,009 s: ---- ET5CBL: Thread 3: Disposing netlist              ---- 
000,009 s: ---- ET5CBL: Joined 4 optimization threads            ---- 
000,009 s: ---- ET5CBL: Merging DADB database                    ---- 
000,009 s: ---- ET5CBL: CBL Done                                 ---- 
000,009 s: Propagation round 1...
000,009 s: Propagating and accelerating 373252 primitives
000,009 s: ....
000,009 s: Propagation round 2...
000,009 s: Propagating and accelerating 366568 primitives
000,009 s: ....
000,009 s: Cleaning up...
000,010 s: Retiming...
000,010 s: Checking for redundant memory ports...
000,010 s: 0 ports removed
000,010 s: Removing complex redundancies... 1  boxes removed
000,010 s: Checking force nets ...
000,010 s: 0 buffer inserted
000,010 s: INFO (db2util-1073): DAS I/O 73 inputs
000,010 s: INFO (db2util-1074): DAS I/O 146 outputs
000,010 s: INFO (db2util-1071): Netlist optimization gives 35 % reduction.
000,010 s:  (530684 - 187671 = 343013)
000,010 s: INFO (db2util-1119): Available configuration: 1 domains
000,010 s: INFO (db2util-1113): The design contains 343013 ET primitives (boxes).
000,010 s: EDRAMS_PER_CHIP=48
000,010 s: ACTIVE_EDRAMS_PER_P512=8
000,010 s: Palladium Z1 configuration detected...
000,010 s: file_to_tvect: xc_work/mem_placement.constraints
000,010 s: Reading file 'xcva_top.mempreset'...
000,010 s: 
000,010 s: Collecting memory ports and instances...
000,010 s: 
000,010 s: Found 330 memory ports.
000,010 s: 
000,010 s: Found 108 memory instances.
000,010 s: WARNING (db2util-1059): Design contains 47 'DO_NOT_TOUCH' memory instances
000,010 s: 
000,010 s: Instruction usage: 25.0%
000,010 s: Finding mergeable memory (step 1)...
000,010 s: .
000,010 s: 
000,010 s: Finding mergeable memory (step 2)...
000,010 s: 
000,010 s: In total, 2 memory instances are candidates for at least 1 merger
000,010 s: 
000,010 s: 
000,010 s: In total, 2 memory instances were merged into 1 merger.
000,010 s: 
000,010 s: .....
000,010 s: Evaluated for compaction 107 memory instances.
000,010 s: Targeted 107 memory instances to INTRAM, 0 to EXTRAM.
000,010 s: Instruction usage after memory transformation: 25.1 %
000,010 s: INFO (db2util-1115): Compilation seed is 262034294
000,011 s: 
000,011 s:     Systems:     1 .
000,011 s:       Racks:     1 .
000,011 s: BrdClusters:     1 .
000,011 s:      Boards:     1 .
000,011 s:       Asics:     1 .
000,012 s:       P512s:     6 ......
000,013 s:        P64s:    48 ................................................
000,013 s: Reducing hop at epc level.
000,014 s: CPR round  1, maxlvl 172, path head 367235 lvl 172, tail  80135, len  86, m_is_marked   0, moved 24, NC 0 
000,014 s: CPR round  2, maxlvl 164, path head  30820 lvl 158, tail  76789, len  84, m_is_marked   0, moved 27, NC 0 
000,014 s: CPR round  3, maxlvl 152, path head  30820 lvl 142, tail  83138, len  70, m_is_marked   0, moved 36, NC 0 
000,014 s: CPR round  4, maxlvl 149, path head 367235 lvl 149, tail  78302, len  95, m_is_marked   0, moved  7, NC 0 
000,014 s: CPR round  5, maxlvl 149, path head 367235 lvl 149, tail  78302, len  94, m_is_marked   0, moved  7, NC 1 
000,014 s: CPR round  6, maxlvl 146, path head 367235 lvl 145, tail  78302, len  94, m_is_marked   0, moved  6, NC 0 
000,014 s: CPR round  7, maxlvl 145, path head 367235 lvl 145, tail  78302, len  95, m_is_marked   0, moved  2, NC 0 
000,014 s: CPR round  8, maxlvl 145, path head 367235 lvl 145, tail  78302, len  93, m_is_marked   0, moved  3, NC 1 
000,014 s: CPR round  9, maxlvl 145, path head 367235 lvl 144, tail  78302, len  94, m_is_marked   0, moved  1, NC 2 
000,014 s: CPR round 10, maxlvl 144, path head 367235 lvl 144, tail  78302, len  95, m_is_marked   0, moved  1, NC 0 
000,014 s: CPR round 11, maxlvl 144, path head 367235 lvl 144, tail  78302, len  94, m_is_marked   0, moved  2, NC 1 
000,014 s: CPR round 12, maxlvl 144, path head 367235 lvl 144, tail  78302, len  93, m_is_marked   0, moved  1, NC 2 
000,014 s: CPR round 13, maxlvl 144, path head 367235 lvl 143, tail  78302, len  93, m_is_marked   0, moved  1, NC 3 
000,014 s: CPR round 14, maxlvl 143, path head 367235 lvl 143, tail  78302, len  93, m_is_marked   0, moved  2, NC 0 
000,014 s: CPR round 15, maxlvl 143, path head 367235 lvl 143, tail  78302, len  95, m_is_marked   0, moved  1, NC 1 
000,014 s: CPR round 16, maxlvl 143, path head 367235 lvl 143, tail  78302, len  94, m_is_marked   0, moved  3, NC 2 
000,014 s: CPR round 17, maxlvl 143, path head 367235 lvl 143, tail  78302, len  95, m_is_marked   0, moved  0, NC 3 
000,014 s: Total relocated = 122
000,014 s: Maximum number of hops in all paths = 143
## et3compile exits at 05/20/2024 11:38:09 Status: 0, PID: 3891942
## et3compile Elapsed time: 0:00:13, CPU time: 0:00:23.73, Memory Usage: 2.2G
000,014 s: 0 262034294 -1 0 0
000,014 s: ^D
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):     1007      448      558        0        0      201
Swap (GB):      127        1      126
* Load info:
  1419 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
              10.52 ( 11% CPU) |   6.82 (  7% CPU) |   4.11 (  4% CPU)
System info: hsv-sc49 - xeCompile - 3891942 3891933 - qtExit - 2024-05-20 11:38:09 - 10.52 11% 6.82 7% 4.11 4% - 1007 448 558 201 127 1 126
Peak usage info for xeCompile (pid 3891942, ppid 3891933) on hsv-sc49: CPU usage 0.00, Peak mem (Res 1 GB, Virt 2 GB), freePhyMem 559 GB, totalPhyMem 1007 GB, freeSwap 127 GB, totalSwap 128 GB
DRM memory info: hsv-sc49 - xeCompile - 3891942 - 3891933 - unknown unlimited
## xeCompile exits at 05/20/2024 11:38:09 Status: 0, PID: 3891942
## xeCompile Elapsed time: 0:00:14, CPU time: 0:00:23.88, Memory Usage: 2.2G
## Child Proc. CPU time: 0:00:00.33
