Build construct file 'dbFiles/constructInfoFile'
117 cells have construct info. Build 69 cells.
 Build construct map total time 0 real, 0.01 cpu(0.01u+0s), 0%, memory 9186M
 Build generate map for 0 cells.

m_numConstructs=712 m_numNewProbed=712
m_createChannels=false
m_constructCells 69:
Probes are in 137 instances
0 interfaces, 0 modports, 0 generates, 0 nlExport, 74 nlImport, 0 oddNames,0 generate1, 0 rangedInstances, 70 cellmodules
 