INFO (tich-1014): Generating ctl file for ice mode
Generating Orion connection in precompile.
noTailgate is set. Skip generating ADC section in ctl.
noTailgate is set. Skip generating multi sample section in ctl.
Generate STB TIE_SOURCELESS section in ctl file
Get design primary io terminals of tie sourceless.
Reading file 'io.pinmap' 
Reading ./dbFiles/xcva_top.pinmap file...
Get design primary io terminals' pull value.
Reading I/O pull value file...
Applying terminalWeakDrive userData
Get design primary bidir io terminals' pull value.
Reading dbFiles/xcva_top.tieSourceless file...
Finish generating STB TIE_SOURCELESS section in ctl file
