et3compile xcva_top -ppcPhase2 <Version> V23.03.131.s001


Begin `et3compile' run...

INFO (db2util-1108): Physical data capture trace depth is 4391552.
INFO (db2util-1067): This design is scheduled in 160 steps.
INFO (qt2dadb-1086): Maximum emulator operating speed is 3069 kHz.
Elapsed_Time    = 00:00:01.14
User_Time       = 00:00:01.14
System_Time     = 00:00:00.12

End `et3compile' run: status 0

