et3compile xcva_top -ppcPhase2 <Version> V23.03.131.s001


Begin `et3compile' run...

INFO (db2util-1108): Physical data capture trace depth is 4387072.
INFO (db2util-1067): This design is scheduled in 164 steps.
INFO (qt2dadb-1086): Maximum emulator operating speed is 2998 kHz.
Elapsed_Time    = 00:00:01.01
User_Time       = 00:00:01.01
System_Time     = 00:00:00.21

End `et3compile' run: status 0

