

======= Dump SST2Writer to file trace.shm/trace_hw at Thu May  9 14:44:34 2024
 
 The top cell  type is Verilog.
Total 2 channel sets.
===== Channel set 0: [startCh 64] startTime 0

The series 'trace_hw_channelSet0' : cyclePeriod 1, unit -12, time period [0 395625]

TotalChannels=29250 WrittenTimes=0 

===== Channel set 1: [startCh 29314] startTime 0

The series 'trace_hw_channelSet1' : cyclePeriod 1, unit -12, time period [0 395625]

TotalChannels=25071 WrittenTimes=0 

Total 1 blocks, 722 vectors, 54385 channels.
 ----- Block 0
vectors: 722 time stamp: [0 .. 395625]
End of Dump SST2Writer.

Write out annotations:
Signature: 1715291067
Emulation Mode: Palladium UXE 15.1 Version ICE_TRACE 
Is1Xmode Sample Frequency: 1000000000000.000000
Waveform time scale: 1 '-12'
Clock Frequency: 1000000000000.000000
Other Annotation: NONE


======= Dump SST2Writer to file trace.shm/trace_hw at Mon May 20 11:39:25 2024
 
 The top cell  type is Verilog.
Total 2 channel sets.
===== Channel set 0: [startCh 64] startTime 0

The series 'trace_hw_channelSet0' : cyclePeriod 1, unit -12, time period [0 395625]

TotalChannels=29250 WrittenTimes=0 

===== Channel set 1: [startCh 29314] startTime 0

The series 'trace_hw_channelSet1' : cyclePeriod 1, unit -12, time period [0 395625]

TotalChannels=25071 WrittenTimes=0 

Total 1 blocks, 720 vectors, 54385 channels.
 ----- Block 0
vectors: 720 time stamp: [0 .. 395625]
End of Dump SST2Writer.

Write out annotations:
Signature: 1716230357
Emulation Mode: Palladium UXE 15.1 Version ICE_TRACE 
Is1Xmode Sample Frequency: 1000000000000.000000
Waveform time scale: 1 '-12'
Clock Frequency: 1000000000000.000000
Other Annotation: NONE
